#------------------------------------------------------------------------
# Source File Information (DO NOT MODIFY)
# Source ID: 2c19000d-8da2-4367-9551-5ff8f4ecaf7c
# Source File: testTAB2.pff
#------------------------------------------------------------------------
#========================================================================
# Code Generated By: SAPIEN Technologies, Inc., PrimalForms 2011 v2.0.15
# Generated On: 23/11/2011 18:57
# Generated By: toto
#========================================================================
#----------------------------------------------

#region Application Functions
function OnApplicationLoad {
	#Note: This function is not called in Projects
	#Note: This function runs before the form is created
	#Note: To get the script directory in the Packager use: Split-Path $hostinvocation.MyCommand.path
	#Note: To get the console output in the Packager (Windows Mode) use: $ConsoleOutput (Type: System.Collections.ArrayList)
	#Important: Form controls cannot be accessed in this function
	#TODO: Add snapins and custom code to validate the application load	
	[void] [System.Reflection.Assembly]::LoadWithPartialName("System.Windows.Forms")
	$objNotifyIcon = New-Object System.Windows.Forms.NotifyIcon 
	#$objNotifyIcon.Icon = "C:\Users\thomas.laromiguiere.FRSONEPAR\Desktop\PS\warn.ico"
	$objNotifyIcon.BalloonTipIcon = "Info" 
	$objNotifyIcon.BalloonTipText = "function OnApplicationLoad ." 
	$objNotifyIcon.BalloonTipTitle = "Info" 
	$objNotifyIcon.Visible = $True 
	$objNotifyIcon.ShowBalloonTip(10000)
	#Get-ChildItem C:\Windows
	return $true #return true for success or false for failure
}
function OnApplicationExit {
	#Note: This function is not called in Projects
	#Note: This function runs after the form is closed
	#TODO: Add custom code to clean up and unload snapins when the application exits	
	$script:ExitCode = 0 #Set the exit code for the Packager
}
#endregion Application Functions


# Generated Form Function
function Call-testTAB_pff {
	#region Import the Assemblies
	[void][reflection.assembly]::Load("System.DirectoryServices, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a")
	[void][reflection.assembly]::Load("System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089")
	[void][reflection.assembly]::Load("System.Data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089")
	[void][reflection.assembly]::Load("System.Xml, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089")
	[void][reflection.assembly]::Load("System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a")
	[void][reflection.assembly]::Load("System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089")
	[void][reflection.assembly]::Load("mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089")
	#endregion Import the Assemblies
	#region Generated Form Objects
	[System.Windows.Forms.Application]::EnableVisualStyles()
	$formAuditIP = New-Object System.Windows.Forms.Form
	$tabcontrol = New-Object System.Windows.Forms.TabControl
	$tabpageAudite = New-Object System.Windows.Forms.TabPage
	$tabpageparam = New-Object System.Windows.Forms.TabPage
	$progressbar2 = New-Object System.Windows.Forms.ProgressBar
	$buttonFileSearch = New-Object System.Windows.Forms.Button
	$richtextboxFileSearch = New-Object System.Windows.Forms.RichTextBox
	$progressbar = New-Object System.Windows.Forms.ProgressBar
	$labelDelai = New-Object System.Windows.Forms.Label
	$richtextbox = New-Object System.Windows.Forms.RichTextBox
	$textboxDelai = New-Object System.Windows.Forms.TextBox
	$pictureboxExel = New-Object System.Windows.Forms.PictureBox
	$trackbarDelai = New-Object System.Windows.Forms.TrackBar
	$statusbar = New-Object System.Windows.Forms.StatusBar
	$labelFileSearch = New-Object System.Windows.Forms.Label
	$labelFin = New-Object System.Windows.Forms.Label
	$labelDebut = New-Object System.Windows.Forms.Label
	$comboboxFin = New-Object System.Windows.Forms.ComboBox
	$comboboxDebut = New-Object System.Windows.Forms.ComboBox
	$checkboxDNS = New-Object System.Windows.Forms.CheckBox
	$buttonLancer = New-Object System.Windows.Forms.Button
	$notifyicon = New-Object System.Windows.Forms.NotifyIcon
	$errorprovider = New-Object System.Windows.Forms.ErrorProvider
	$InitialFormWindowState = New-Object System.Windows.Forms.FormWindowState
	#endregion Generated Form Objects
	#region Control Helper Functions
	function Show-NotifyIcon{
	<#
		.SYNOPSIS					Displays a NotifyIcon's balloon tip message in the taskbar's notification area.
		.DESCRIPTION				Displays a NotifyIcon's a balloon tip message in the taskbar's notification area.
		.PARAMETER BalloonTipText 	Sets the text to display in the balloon tip.
		.PARAMETER BalloonTipTitle	Sets the Title to display in the balloon tip.
		.PARAMETER BalloonTipIcon	The icon to display in the ballon tip.
	#>
		 param(
		  [Parameter(Mandatory = $true, Position = 0)]
		  [ValidateNotNull()]
		  [System.Windows.Forms.NotifyIcon]$NotifyIcon,
		  [Parameter(Position = 1)]
		  [String]$BalloonTipText,
		  [Parameter(Position = 2)]
		  [String]$BalloonTipTitle,
		  [Parameter(Position = 3)]
		  [System.Windows.Forms.ToolTipIcon]$BalloonTipIcon)
		if($NotifyIcon.Icon -eq $null){
			#Set a Default Icon otherwise the ballon will not show
			$NotifyIcon.Icon = [System.Drawing.Icon]::ExtractAssociatedIcon([System.Windows.Forms.Application]::ExecutablePath)
		}
		if($BalloonTipText -ne $null -and $BalloonTipText.Length -ne 0){
			$notifyicon.BalloonTipText = $BalloonTipText	
		}
		if($BalloonTipTitle -ne $null -and $BalloonTipTitle.Length -ne 0){
			$notifyicon.BalloonTipTitle = $BalloonTipTitle	
		}
		if($BalloonTipIcon -ne $null -and $BalloonTipIcon.Length -ne 0){
			$notifyicon.BalloonTipIcon = $BalloonTipIcon	
		}
		$notifyicon.ShowBalloonTip(0)
	}
	function Load-ComboBox {
	<#
		.SYNOPSIS				This functions helps you load items into a ComboBox.
		.DESCRIPTION			Use this function to dynamically load items into the ComboBox control.
		.PARAMETER  ComboBox	The ComboBox control you want to add items to.
		.PARAMETER  Items		The object or objects you wish to load into the ComboBox's Items collection.
		.PARAMETER  DisplayMember	Indicates the property to display for the items in this control.
		.PARAMETER  Append		Adds the item(s) to the ComboBox without clearing the Items collection.
		.EXAMPLE				Load-ComboBox $combobox1 "Red", "White", "Blue"
		.EXAMPLE				Load-ComboBox $combobox1 "Red" -Append
								Load-ComboBox $combobox1 "White" -Append
								Load-ComboBox $combobox1 "Blue" -Append
		.EXAMPLE				Load-ComboBox $combobox1 (Get-Process) "ProcessName"
	#>
		Param (
			[Parameter(Mandatory=$true)]
			[System.Windows.Forms.ComboBox]$ComboBox,
			[Parameter(Mandatory=$true)]
			$Items,
		    [Parameter(Mandatory=$false)]
			[string]$DisplayMember,
			[switch]$Append)
		if(-not $Append){
			$comboBox.Items.Clear()	
		}
		if($Items -is [Array]){
			$comboBox.Items.AddRange($Items)
		}
		else{
			$comboBox.Items.Add($Items)	
		}
		$comboBox.DisplayMember = $DisplayMember	
	}
	#endregion Control Helper Functions
	#region Form Events
	$formAuditIP_Load={
		#TODO: Initialize Form Controls here
		$statusbar.Text="initialisation"
		$textboxDelai.Text=$trackbarDelai.Value
		$errorprovider.SetIconAlignment($buttonFileSearch, [System.Windows.Forms.ErrorIconAlignment]::MiddleLeft)
	    $errorprovider.SetError($buttonFileSearch, "choix du fichier EXE");
		$richtextboxFileSearch.Text="choix du fichier EXEL"
	}
	$textboxDelai_TextChanged={
		#TODO: Place custom script here
		$statusbar.Text="textboxDelai_TextChanged :" + $textboxDelai.Text
		$trackbarDelai.Value=$textboxDelai.Text
	}	
	$trackbarDelai_Scroll={
		#TODO: Place custom script here
		$statusbar.Text="trackbarDelai_Scroll :" + $trackbarDelai.Value
		$textboxDelai.Text=$trackbarDelai.Value
	}
	$buttonFileSearch_Click={
		#TODO: Place custom script here
		$statusbar.Text="buttonFileSearch_Click"
		$errorprovider.SetIconAlignment($buttonFileSearch, [System.Windows.Forms.ErrorIconAlignment]::MiddleLeft)
	    $errorprovider.SetError($buttonFileSearch, "");		
		[void] [Reflection.Assembly]::LoadWithPartialName( 'System.Windows.Forms' )    
		$fileDialogBox = New-Object Windows.Forms.OpenFileDialog     
		$fileDialogBox.filter = "fichier Exel (*.xls*)| *.xls*"     
		$fileDialogBox.ShowDialog( )    
		$richtextboxFileSearch.Text=$fileDialogBox.filename
			
		$statusbar.Text="openExel :" + $fileDialogBox.filename
		$excel= new-object -comobject excel.application
		$excel.Visible = 0
		$classeur=$excel.workbooks.open($fileDialogBox.filename)
		$statusbar.Text=$fileDialogBox.filename + " nb_worksheet :" + $excel.Sheets.Count
	  
	    $comboboxDebut.Items.Clear();
	    $comboboxDebut.Text = "";
		$comboboxFin.Items.Clear();
	    $comboboxFin.Text = "";
		$comboboxFin.Visible=0
		$buttonLancer.Visible=0
		$checkboxDNS.CheckState=0
		$errorprovider.SetError($comboboxDebut, "");
		$errorprovider.SetError($comboboxFin, "");
		
		$sheet_debut=1
	    $sheet_fin = $excel.Sheets.Count
		$progressbar.Value=0
		$progressbar.Minimum = 0
	    $progressbar.Maximum = $sheet_fin - $sheet_debut + 1
	    $progressbar.step = 1
		$progressbar.Visible=1
		for ($i=$sheet_debut; $i -le $sheet_fin; $i++){
			$comboboxDebut.Items.add($excel.worksheets.item($i).name)
			$comboboxFin.Items.add($excel.worksheets.item($i).name)
			$progressbar.PerformStep()	
			}
		$progressbar.Visible=0         
	    $comboboxDebut.Visible=1
		$statusbar.Text="comboboxDebut_items :" + $progressbar.Maximum
		$excel.quit()
		$excel=$null
		$errorprovider.SetIconAlignment($comboboxDebut, [System.Windows.Forms.ErrorIconAlignment]::MiddleLeft)
	    $errorprovider.SetError($comboboxDebut, "choisir la feuille de début de l'audite IP");
	}
	$comboboxDebut_SelectedIndexChanged={
		#TODO: Place custom script here
		$statusbar.Text="comboboxDebut_SelectedIndexChanged" + $comboboxDebut.SelectedIndex
		$errorprovider.SetIconAlignment($comboboxDebut, [System.Windows.Forms.ErrorIconAlignment]::MiddleLeft)
	    $errorprovider.SetError($comboboxDebut, "");
		$comboboxFin.SelectedIndex=$comboboxDebut.SelectedIndex
		$comboboxFin.Visible=1
		$errorprovider.SetIconAlignment($comboboxFin, [System.Windows.Forms.ErrorIconAlignment]::MiddleLeft)
	    $errorprovider.SetError($comboboxFin, "choisir la feuille de fin de l'audite IP");
	}
	$comboboxFin_SelectedIndexChanged={
		#TODO: Place custom script here
		$statusbar.Text="comboboxFin_SelectedIndexChanged :" + $comboboxFin.SelectedIndex
		$errorprovider.SetError($comboboxFin, "");
		if ($comboboxFin.SelectedIndex -lt $comboboxDebut.SelectedIndex){
			$comboboxFin.SelectedIndex=$comboboxDebut.SelectedIndex
		}
		$buttonLancer.Visible=1
	}
	$buttonLancer_Click={
		#TODO: Place custom script here
		$statusbar.Text="buttonLancer_Click"
		$errorprovider.SetError($buttonFileSearch, "");
		$errorprovider.SetError($comboboxDebut, "");
		$errorprovider.SetError($comboboxFin, "");
		$excel= new-object -comobject excel.application
		$excel.Visible = 1
		$workbook=$excel.workbooks.open($richtextboxFileSearch.Text)
		$ping = new-object System.Net.NetworkInformation.Ping
		#$Reply = new-object System.Net.NetworkInformation.PingReply
		
		$progressbar.Minimum = 0
	    $progressbar.Maximum = $comboboxFin.SelectedIndex - $comboboxDebut.SelectedIndex + 1
	    $progressbar.step = 1
		$progressbar.Value=0
		$progressbar.Visible=1
		
		For($s=$comboboxDebut.SelectedIndex+1;$s -le $comboboxFin.SelectedIndex+1; $s++){
			$worksheet = $workbook.worksheets.item($s)
			$worksheet.Select
			$statusbar.Text= " Audite :" + $worksheet.Name + " début"
			$lDebut = 2
			$lFin = $lDebut
			$col_adressIP = 0
			$col_reversIP = 0
			$col_checkIP = 0
			$col_date = 0
	
			$range = $worksheet.Range("1:1")
			$result=$range.Find("Adresse IP")
			$col_adressIP=$result.Column
			$result=$range.Find("test_Ping")
			$col_checkIP=$result.Column
			$result=$range.Find("revers_IP")
			$col_reversIP=$result.Column
			$result=$range.Find("date_check")
			$col_date=$result.Column
	#'en cas d'echec le programme s'arrete
			If ($col_adressIP -le 0 -or $col_checkIP -le 0 -or $col_reversIP -le 0 -or $col_date -le 0) {
				$statusbar.Text= "echec recherche champs : col_adressIP=" + $col_adressIP + " ; col_checkIP=" + $col_checkIP + " ; col_reversIP=" + $col_reversIP + " ; col_date=" + $col_date
				$shell = new-object -comobject wscript.shell
	 			$popup = $shell.popup(“erreur de recherche des prerequis dans “ + $worksheet.Name + ":" + $range.tostring() ,0,”Erreur recherche Exel”,2)
				$statusbar.Text= " popup " + $popup
				switch ($popup){ 
	        		3 {$statusbar.Text= " Abandonner";Exit(1)} 
	        		4 {$statusbar.Text= " Recommencer";$s--} 
	        		5 {$statusbar.Text= " Ignorer"} 
	        		default {}
	    		}
			}
			elseif ($true){
				$lFin = ($worksheet.usedRange.rows).count
				$progressbar2.Minimum = $lDebut
	    		$progressbar2.Maximum = $lFin - $lDebut + 1
	    		$progressbar2.step = 1
				$progressbar2.Value = $lDebut
				$progressbar2.Visible=1
				For($l=$lDebut;$l -le $lFin ; $l++){
					$Worksheet.cells.item($l,$col_checkIP).value2 = ""
					$Worksheet.cells.item($l,$col_reversIP).value2 = ""
					$Worksheet.cells.item($l,$col_date).value2 = ""
										
					For($i=1;$i -le 5 ; $i++){
						try{$Reply = $ping.send($Worksheet.cells.item($l,$col_adressIP).Text,$textboxDelai.Text)}
							Catch [System.Net.NetworkInformation.PingException],[System.Net.Sockets.SocketException],[Exception] 
							{
							$statusbar.Text= "EXEPTION PING sur "+$Worksheet.cells.item($l,$col_adressIP).Text
							$Reply = "toto"
							$Worksheet.cells.item($l,$col_checkIP).value2="-"
							$i=5
							}
						finally {}
						
						if (-not $Reply.Equals("toto")){
							if ($Reply.status.tostring -eq "Success"){
								$i=5
							}
						}
					}
					if (-not $Reply.Equals("toto")){
						$Worksheet.cells.item($l,$col_checkIP).value2=$Reply.status.tostring() + " ( " + $Reply.RoundtripTime + "ms)"
						if ($checkboxDNS.CheckState -eq 1){
							try{$Worksheet.cells.item($l,$col_reversIP).value2 = [System.Net.Dns]::GetHostbyAddress($Worksheet.cells.item($l,$col_adressIP).Text).hostname}
								Catch [System.Net.Sockets.SocketException],[Exception] 
								{
								$statusbar.Text= "EXEPTION DNS sur "+$Worksheet.cells.item($l,$col_adressIP).Text
								$Worksheet.cells.item($l,$col_reversIP).value2="-"
								}
							finally {}
						}				
					} 
					$time = Get-Date
					$Worksheet.cells.item($l,$col_date).value2=$time
				$progressbar2.PerformStep()	
				}
			$progressbar2.Visible=0	
			}
		$workbook.Save()
		$progressbar.PerformStep()
		$statusbar.Text= " Audite :" + $worksheet.Name + " fin"
		}
		$progressbar.Visible=0
		$workbook.Save()
		$excel.quit()
		$excel=$null
	}
	
	#$buttonFileSearch_Validating=[System.ComponentModel.CancelEventHandler]{
	#Event Argument: $_ = [System.ComponentModel.CancelEventArgs]
		#TODO: Place custom script here
	#=======================================
		#$errorprovider.SetIconAlignment($buttonFileSearch, [System.Windows.Forms.ErrorIconAlignment]::MiddleLeft)
	
		#Event Argument: $_ = [System.ComponentModel.CancelEventArgs]
	    #Check if the Name field is empty
	    #if($richtextboxFileSearch.Text.Trim() -eq ""){
	        #Display an error message
	    #    $errorprovider.SetError($buttonFileSearch, "choisir un fichier Exel");
	    #}
	    #else{
	        #Clear the error
	    #    $errorprovider.SetError($buttonFileSearch, "choisir un fichier Exel2");
	    #}
		#=======================================	
	#}
	
	#$richtextboxFileSearch_Validating=[System.ComponentModel.CancelEventHandler]{
	#Event Argument: $_ = [System.ComponentModel.CancelEventArgs]
		#TODO: Place custom script here
	#	$errorprovider.SetIconAlignment($richtextboxFileSearch, [System.Windows.Forms.ErrorIconAlignment]::MiddleLeft)
	 #   $errorprovider.SetError($richtextboxFileSearch, "choisir un fichier Exel");
	#$richtextboxFileSearch.Text = "tototottoto"
	#}
	#endregion Form Events
	#region Generated Events
	$Form_StateCorrection_Load={
		#Correct the initial state of the form to prevent the .Net maximized form issue
		$formAuditIP.WindowState = $InitialFormWindowState
	}
	$Form_Cleanup_FormClosed={
		#Remove all event handlers from the controls
		try{
			$buttonFileSearch.remove_Click($buttonFileSearch_Click)
			$textboxDelai.remove_TextChanged($textboxDelai_TextChanged)
			$trackbarDelai.remove_Scroll($trackbarDelai_Scroll)
			$comboboxFin.remove_SelectedIndexChanged($comboboxFin_SelectedIndexChanged)
			$comboboxDebut.remove_SelectedIndexChanged($comboboxDebut_SelectedIndexChanged)
			$buttonLancer.remove_Click($buttonLancer_Click)
			$formAuditIP.remove_Load($formAuditIP_Load)
			$formAuditIP.remove_Load($Form_StateCorrection_Load)
			$formAuditIP.remove_FormClosed($Form_Cleanup_FormClosed)
		}
		catch [Exception]{ }
	}
	#endregion Generated Events
	#region Generated Form Code
	#region formAuditIP
	$formAuditIP.Controls.Add($tabcontrol)
	$formAuditIP.Controls.Add($progressbar2)
	$tabpageAudite.Controls.Add($buttonFileSearch)
	$tabpageAudite.Controls.Add($richtextboxFileSearch)
	$formAuditIP.Controls.Add($progressbar)
	$tabpageparam.Controls.Add($labelDelai)
	$tabpageparam.Controls.Add($richtextbox)
	$tabpageparam.Controls.Add($textboxDelai)
	$tabpageparam.Controls.Add($pictureboxExel)
	$tabpageparam.Controls.Add($trackbarDelai)
	$formAuditIP.Controls.Add($statusbar)
	$tabpageAudite.Controls.Add($labelFileSearch)
	$tabpageAudite.Controls.Add($labelFin)
	$tabpageAudite.Controls.Add($labelDebut)
	$tabpageAudite.Controls.Add($comboboxFin)
	$tabpageAudite.Controls.Add($comboboxDebut)
	$tabpageAudite.Controls.Add($checkboxDNS)
	$tabpageAudite.Controls.Add($buttonLancer)
	$formAuditIP.AcceptButton = $buttonFileSearch
	$formAuditIP.ClientSize = '516, 342'
	$formAuditIP.FormBorderStyle = 'FixedSingle'
	$formAuditIP.HelpButton = $True
	$formAuditIP.Name = "formAuditIP"
	$formAuditIP.Text = "Audit-IP"
	$formAuditIP.TopMost = $false
	$formAuditIP.add_Load($formAuditIP_Load)
	#endregion formAuditIP
	#region tabcontrol
	$tabcontrol.Controls.Add($tabpageAudite)
	$tabcontrol.Controls.Add($tabpageparam)
	$tabcontrol.Location = '0, 7'
	$tabcontrol.Name = "tabcontrol"
	$tabcontrol.SelectedIndex = 0
	$tabcontrol.Size = '516, 307'
	$tabcontrol.TabIndex = 17
	#endregion tabcontrol
	#region tabpageAudite
	$tabpageAudite.Location = '4, 22'
	$tabpageAudite.Name = "tabpageAudite"
	$tabpageAudite.Padding = '3, 3, 3, 3'
	$tabpageAudite.Size = '508, 281'
	$tabpageAudite.TabIndex = 0
	$tabpageAudite.Text = "auditeIP"
	$tabpageAudite.UseVisualStyleBackColor = $True
	#endregion tabpageAudite
	#region tabpageparam
	$tabpageparam.Location = '4, 22'
	$tabpageparam.Name = "tabpageparam"
	$tabpageparam.Padding = '3, 3, 3, 3'
	$tabpageparam.Size = '508, 281'
	$tabpageparam.TabIndex = 1
	$tabpageparam.Text = "parametres et info"
	$tabpageparam.UseVisualStyleBackColor = $True
	#endregion tabpageparam
	#region progressbar2
	$progressbar2.Cursor = "No"
	$progressbar2.Location = '404, 320'
	$progressbar2.Name = "progressbar2"
	$progressbar2.Size = '100, 10'
	$progressbar2.TabIndex = 16
	$progressbar2.Visible = $False
	#endregion progressbar2
	#region buttonFileSearch
	#region Binary Data
	$buttonFileSearch.BackgroundImage = [System.Convert]::FromBase64String('/9j/4AAQSkZJRgABAQEASABIAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEP
ERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4e
Hh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAAwADADASIA
AhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQA
AAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3
ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWm
p6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEA
AwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSEx
BhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElK
U1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3
uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD6suLh
9a4gmmi0wdJIZWje6PYqykMsY7EEF+o+T/WQ/wBi2n/Pzq//AIN7r/45VTwlYWLeFNHZrG1ZmsIC
SYVJJMa89K1P7P0//nwtP+/C/wCFfA4jHSrVHKctfRP7rs6lGyOa1211/wAOagniTw3LqWr20cYj
1LQ57x5jcxAk+ZbNKx2XC7jhchZR8rYIR07Hw7rWl+IdFttZ0a8S7sblS0UqgjoSGVlIDKysCrKw
DKwIIBBFU/7P0/8A58LT/vwv+FZ82iaAzl38P6VvY5bfZxFiTz6d+Rknr612YLOZYeLhK8l06W/P
QTpc70OsorjToegEcaBo5xgkrYxbfX72OmMc47H1FcL8b4rXQPhhrfiTQbGy03WNHt/tthe29rGk
tvOnOQQvAwxRkJIZSVbKsVf0YZ/GTs4aeo/qsrN3PRfB/wDyKOjf9g+3/wDRa1psQqknOAM8DNZf
hEhfCGjE5wNOgPAz/wAs1q9LKuScr8vI+cgY98DsRg+g69cV8lJXmzSMWxJnUqS6qy5IGSpXjdnr
jnAIPp+dRMxXKhumdzdABlgWO08evb8MfKOxDHld2CN2454Jyc8gDPXrgAA5yAK8kgPI2gdQWbP0
JPHIGBkEdV5OcjSMTphASVy3JyTjjd94cHv2IOe3ynODgEV55+0e274HeMNqtt/s2XGBxjauCM9B
6Dtvxx376Rj0+ZQOoI+ZR2yCCOmcj0zgYzu87/aKbd8EfF7fL/yDJQed2D3556nJHPYnvXRCJvKP
uP0O18OeINDtfDej29xrGnRSx2NuHSS6VWUmNRgj8+vt9ast4l0ELzrmmsVVSQbyPHGCP4jk5z05
x6nGV/4VP8LP+iaeDP8AwRW3/wARR/wqf4Wf9E08Gf8Agitv/iK9p8OSvf2q/wDAf/tjyo4hR6ED
+ItBLbRr2mkgjk3afNhsA5yRgEZx6c85IMLeItDY4GuafktjP2pM557lj1wMHJx1PRcXf+FT/Cz/
AKJp4M/8EVt/8RR/wqf4Wf8ARNPBn/gitv8A4iqXD81/y9X/AID/APbGqxtvsmY+v6Du2nWNN2g5
wJ0I59Me305I6ba4L4/avpl58GfFkVvqNnPMdLkwqXIdidpJwM59SevP1r1D/hU/ws/6Jp4M/wDB
Fbf/ABFT2Hwy+G1hfW99Y/D3wla3dtKs0E8OjW6SROpyrqwTKsCAQRyCK0WRTX/Lxf8AgP8A9sXL
MG4tcu5//9k=')
	#endregion
	$buttonFileSearch.BackgroundImageLayout = 'Zoom'
	$buttonFileSearch.Cursor = "Hand"
	$buttonFileSearch.FlatAppearance.BorderSize = 0
	$buttonFileSearch.FlatStyle = 'Flat'
	$buttonFileSearch.Location = '441, 12'
	$buttonFileSearch.Name = "buttonFileSearch"
	$buttonFileSearch.Size = '26, 29'
	$buttonFileSearch.TabIndex = 15
	$buttonFileSearch.UseVisualStyleBackColor = $True
	$buttonFileSearch.add_Click($buttonFileSearch_Click)
	#endregion buttonFileSearch
	#region richtextboxFileSearch
	$richtextboxFileSearch.Location = '33, 23'
	$richtextboxFileSearch.Name = "richtextboxFileSearch"
	$richtextboxFileSearch.ReadOnly = $True
	$richtextboxFileSearch.Size = '434, 18'
	$richtextboxFileSearch.TabIndex = 14
	$richtextboxFileSearch.Text = ""
	#endregion richtextboxFileSearch
	#region progressbar
	$progressbar.Cursor = "No"
	$progressbar.Location = '404, 333'
	$progressbar.Name = "progressbar"
	$progressbar.Size = '100, 10'
	$progressbar.TabIndex = 13
	$progressbar.Visible = $False
	#endregion progressbar
	#region labelDelai
	$labelDelai.AutoSize = $True
	$labelDelai.Location = '365, 145'
	$labelDelai.Name = "labelDelai"
	$labelDelai.Size = '115, 39'
	$labelDelai.TabIndex = 12
	$labelDelai.Text = "delai ping en ms :
sur LAN delai 200ms
sur WAN delai 1000ms"
	#endregion labelDelai
	#region richtextbox
	$richtextbox.BackColor = 'InactiveCaptionText'
	$richtextbox.BorderStyle = 'None'
	$richtextbox.Location = '33, 83'
	$richtextbox.Name = "richtextbox"
	$richtextbox.Size = '242, 72'
	$richtextbox.TabIndex = 11
	$richtextbox.Text = "Ce formulaire lance une script realisant un audite des adresses IP. (attention les ping réalisés utilisent les droits de la machine local d'execution)
chaque test comporte 5 ping, 1 ping ok poru résultat positif."
	#endregion richtextbox
	#region textboxDelai
	$textboxDelai.Location = '475, 187'
	$textboxDelai.Name = "textboxDelai"
	$textboxDelai.Size = '30, 20'
	$textboxDelai.TabIndex = 10
	$textboxDelai.add_TextChanged($textboxDelai_TextChanged)
	#endregion textboxDelai
	#region pictureboxExel
	#region Binary Data
	$pictureboxExel.BackgroundImage = [System.Convert]::FromBase64String('/9j/4AAQSkZJRgABAAEAYABgAAD/4QB2RXhpZgAATU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAA
AZKGAAcAAABAAAAALAAAAABVTklDT0RFAABMAEUAQQBEACAAVABlAGMAaABuAG8AbABvAGcAaQBl
AHMAIABJAG4AYwAuACAAVgAxAC4AMAAxAAD//gAfTEVBRCBUZWNobm9sb2dpZXMgSW5jLiBWMS4w
MQD/2wBDAAgFBgcGBQgHBgcJCAgJDBQNDAsLDBgREg4UHRkeHhwZHBsgJC4nICIrIhscKDYoKy8x
MzQzHyY4PDgyPC4yMzH/2wBDAQgJCQwKDBcNDRcxIRwhMTExMTExMTExMTExMTExMTExMTExMTEx
MTExMTExMTExMTExMTExMTExMTExMTExMTH/wAARCAB6Ak8DAREAAhEBAxEB/8QAHwAAAQUBAQEB
AQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1Fh
ByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZ
WmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXG
x8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAEC
AwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHB
CSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0
dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX
2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD0220TTJLeJ3soizICTjqcVZJJ/YOl
f8+MX5UWAT+wtJ3bfsUOcZxiiwC2mlad5JBsbY4dwMxKTgMfaiwE39lad/0D7X/vyv8AhRYA/srT
v+gfa/8Aflf8KLAH9lad/wBA+1/78r/hRYDM1AWVprel6emkae6X3m7pGeKN49ihhtjI3SZ77fu9
TXXRw0alCpVbacLaWbTu7avaPz32RLlZpE1kfDd9IkdidKuXeMyqsPluWQNtLADqNwIz0zxUVMLW
opupBpJ21TWtr29ba+g1JPZmYmteG59etdMs7fTbpbiPeJ4TGyg5YAAAcjKkE54JUd6UsNWp83tI
ONtNU1ra9vXld/TXoNuyTX9La/36GgJ/C/kwzCXR/KnWR4n3RbZFQZcqe4UA5x0xzVfU8RzOPs5X
Vr6PS+1/Xp3FzLuM8OXPh7xHpv2/SrW1lg8x48mFQQVYjkdRkYYA4OGHAzVYzBVcFV9lWVnZP7/z
ts7aXTFGSkro0/7K07/oH2v/AH5X/CuSxQf2Vp3/AED7X/vyv+FFgD+ytO/6B9r/AN+V/wAKLAY3
i6ws7fSoHgtIImOoWKFkjCkq11ErDjsQSCO4JFIDZ/srTv8AoH2v/flf8KdgD+ytO/6B9r/35X/C
iwB/ZWnf9A+1/wC/K/4UWAP7K07/AKB9r/35X/CiwB/ZWnf9A+1/78r/AIUWAxtO1XwpqV7HaWSW
skk3meSxtCsc/lnD+W5ULJj/AGSeOeld9bLcTQg6lSFkrX1V1fa6TvG/mkSpp6IZb614SuYbCW2j
t5V1JZmtQlixaURAmTChM5GDxjJ7Zqp5XiqcpxlG3Jy82q05ttb21/DrYOdHOW/jnSJdPttQk0LT
7e2u3mFukpZZpRF97aPJ2FsEYG/BY7Qc5rqr5HiqNWVOKUuXl5mmtOb1adk73btouZpIhVYtXvY6
m11DwtdNpa2y2Uh1ZXaz22+RIEGX5xhSO4ODnI61xTy/EU1UcoW9nbm20vt638r99i1NO3mZo8Te
GJ9Q0O20/Tlu49aaQRTpZMEVU3Anlck7hgjsMsSBjPX/AGNiIU606touna6ur628+zv5vRXd7T7R
XVup1H9lad/0D7X/AL8r/hXjWNA/srTv+gfa/wDflf8ACiwB/ZWnf9A+1/78r/hRYA/srTv+gfa/
9+V/wosAf2Vp3/QPtf8Avyv+FFgM+PTLJru8H2O3wsoAHlLwNiH096+SzOvVhiZRjJpabN9j1KEI
Omm1/VyX+yrH/nyt/wDv0v8AhXnfWq/87+9m3JD+VB/ZVj/z5W//AH6X/Cj61X/nf3sOSH8qD+yr
H/nyt/8Av0v+FH1qv/O/vYckP5UH9lWP/Plb/wDfpf8ACj61X/nf3sOSH8qD+yrH/nyt/wDv0v8A
hR9ar/zv72HJD+VB/ZVj/wA+Vv8A9+l/wo+tV/5397Dkh/Kg/sqx/wCfK3/79L/hR9ar/wA7+9hy
Q/lQf2VY/wDPlb/9+l/wo+tV/wCd/ew5IfyoP7Ksf+fK3/79L/hR9ar/AM7+9hyQ/lRQ19tH0HSL
nU7+0hFvbLltkAZiSQAAPUkgenPOBXfltHHZnioYTDzfNJ6Xk0u7b8kk337JvQio6VKLlJKy8jIu
vEWg2Vhq1xeaPLBLpDRC6tmgiMiiTGwgqxUg5/vZGD7Z9ijkeY4ith6VGupRrqXLLmmo+5fmTvFS
TVv5bO6s97YutRjGTcfhtdWXUreK/EenaPZ66LHRUuLvR/IWQvEixAzDKN1yQOMgDOSO2WHTk2RY
nHVcL7fEcsK/O1Zycv3b95bWTfRt2td72i5rVqdNS5Yaxt26lS98baTb3V6IvDvmW2mtEt9KVQGE
u204ABVtrYGN2Sc4yAWDw/DmYYinSnDEK9Xn5FzS97k9bNXSbTaslbmcW0mqtenTbXJta+2l/wDL
8/vNbVPEHh/TRrRn0x2/sXyPtGy3T5vOxt25I6Z5zj8a48HkuZYv6r7Osl7fn5bylpyb3snvbS1/
kXKtRjzXj8Nunck0a8h1HxZrWkPocMEOmLFiUpGSzMCcnB4BGCoAPAO4gkLWePwU8JlmGxscQ5Sq
uWl5aJWWmm6d1JtrVrlTScm6coyqyhyLS3Y6D+yrH/nyt/8Av0v+FfPfWq/87+9nRyQ/lQf2VY/8
+Vv/AN+l/wAKPrVf+d/ew5IfyoP7Ksf+fK3/AO/S/wCFH1qv/O/vYckP5UH9lWP/AD5W/wD36X/C
j61X/nf3sOSH8qD+yrH/AJ8rf/v0v+FH1qv/ADv72HJD+VB/ZVj/AM+Vv/36X/Cj61X/AJ397Dkh
/Kg/sqx/58rf/v0v+FH1qv8Azv72HJD+VB/ZVj/z5W//AH6X/Cj61X/nf3sOSH8qD+yrH/nyt/8A
v0v+FH1qv/O/vYckP5UH9lWP/Plb/wDfpf8ACj61X/nf3sOSH8qIpNMslu7MfY7cBpSCPKXkbHPp
7V6OWV6s8TGMpNrXq+xjXhBU20v6uaH9lad/0D7X/vyv+FfW2PLD+ytO/wCgfa/9+V/wosAf2Vp3
/QPtf+/K/wCFFgD+ytO/6B9r/wB+V/wosAf2Vp3/AED7X/vyv+FFgKV0fDdpexWV0dKgu5seXBJ5
ayPk4GFPJyeBjvXRDC1qkHUhBuK3aTsvVi5ktLhOfDdt9p+0HSofsez7Rv8ALXyd33d+fu57Z60Q
wtafLywb5r20ett7d7dbbBzJdTBuvEGijWtQ06xtNBYabGjXM13crbqjMxUqP3bA7TtBOeCwHXiu
h5XjFShV9m2p35Ulduyve3nrbuk3tqLnje1zWsLzw9c6TJqE8Gn2cdvIYbnzhGot5Q20ox6A5I+u
R61zrC1ZSjGMG3JXSs7tNXukPmte/Qj1/VPCug2V5c366fmz2iSCNI2l3MCUTb1ywBIzjgE9ATW+
Ey3E4ucIU4P3r2bWllu79l1+7fQTmo7mtBp+k3EMc0FpZSxSKHR0jRlZSMgggcgiuKUHCTjJWaKu
P/srTv8AoH2v/flf8KmwB/ZWnf8AQPtf+/K/4UWAP7K07/oH2v8A35X/AAosAf2Vp3/QPtf+/K/4
UWAP7K07/oH2v/flf8KLATWX/HnB/wBc1/lQA+QsqEou5uwzigCpZxXAumlnXGVx1HqKALFp/qm/
66P/AOhGgCWgAoAKAOa1/Sr278b+F9Rt4d9pYfa/tEm5Rs3xhV4Jycn0zXr4TE0qeBxNGT96fJZd
7O7/AKZnJPmTOX8H+D9V0pvBbz6ckDac1+9+VePKtICIycH5iQFHGcADOMV7OY5ph66xijO/P7Pl
3+zq7X21vvYiMGuX5nMeBPBup6tpeg39kWt4YDdXXn+Ym3zchIwBt3bt0Y3A5XaAQwJKjrz7HQoy
xVLmbnL2aUe1veeu1nf1u3pbVzSpqTV9jpfB3hnxBY3Xg1L7S/Ig0X7cLiU3EbHMoYqQoJ+XlRnr
ndkAAFuXMMxwlanipU53dX2dlZ/ZtdX77+W1m9UqjGSa8rnVfDbSr3QvCNtpOpQ+VPZySoWDKySg
yMwdSDnBDfxAHg8V4uc4mli8ZKvSd1JJ+a0Ss/PTpdeZdNOMbM6WvINAoAKAMPxr/wAga3/7Cen/
APpZDQBuUAFABQAUAFAHBeGPBGpaVe+Hkup7Q2nh/wC1+XLG7GS584nGUKgR4BycM3Ix719Pjs3o
V4V3BPmq8l07Wjy9nd3v6IxjBq3kM8N+B9X0nUPDQmurGSy0FrxQU3iSVZd21sYwDyAV7bSdzZwK
xmcYfEU8RyxkpVeTtZctrrv03632VrsjBpryOKuvCuo6ZqHhvQo9Kt0vhJfxxXb7MXaFQVkO1tyl
QSRnJXAI3H5a7HjKWPw+LxDTipKlfa6adtHrzJWv9m+3u7iUfZySeq1/LY7jS/A2paTZeFPsl5aS
Xeh/aRJ5isIz54OWGOW2E8A7dw7pXDXzihiJ4nni1Gry2ta/ud+3N315e0hqDVvIPD3gjUtJtvCL
PPaST6FJdCdA7BHSYtllbbnKgjggA88jqTF5vQxEsUkmlVUbbXTjbdX2fe+nZhGDVvI72vmDYKAC
gAoAKAKdou66vj/03H/otK+MzX/epfL8j06LtTj/AF1ZZ8uvNNOYPLoDmDy6A5g8ugOYPLoDmDy6
A5g8ugOYPLoDmDy6A5jK8V+H4/Efh680maZ4FuVAEiAEqwYMpx3GQMjjIzyOterk2ZTynHU8ZCKk
430fVNNP00bs9bPo9jOrBVYODMS88A/2jZeIU1LUd11rnk75beDy44vKA8vCFmJ5GT83I4GOte3Q
4n+qVcI8NStDD89lKV2+dvmvJKK2fu+7o9XfYxlQ5lPmesrfgMu/h81/D4jXUNWeWTXVg3OkATyX
iHGBk5XOOOu0YLE/NV0eKVhp4N4egksPz2Tk3zKe93ZWdr67czuope6J0OZT5n8VvwOQk8F6/can
4r0pVmaLUJbZmuvIWO3kGfMJBZtwKnj5d+PmBBJUj34Z/g8Fg8BXppOVNVbLmvKN3yrmsrNNO+qg
20mmldPGVJzqVF0dv83+Prp0Z13iP4fSaxJrLRau1ouspb/aFFuH+eHpjJGFI7dcgHdjKnwcr4pj
gI4ZToc7oOfK+ZrSe99H7yfXblbXLe0lrUw7nze9a9r/AC/r/gm5YeHvsPifU9XhucpqccQmgaPl
XjBVWVs8DaeQQTnnPavDxOZ/WMuoYKcNaTlZp7qTu01be+zTStpbqbxhy1JTT3/Q2PLrxzXmDy6A
5g8ugOYPLoDmDy6A5g8ugOYPLoDmDy6A5g8ugOYPLoDmK12u26sT/wBNz/6LevSyr/eo/P8AIzrO
9OX9dUXK+zPMCgAoAKACgDzXxf4V1q+vfFUFlZedH4g+w+TcCVFjg8ogP5gJDds/KrcH14r6/L8y
wtGGGlUlZ0vaXVnd823LZW+9owlBu9uthnjXwtr93N4uTTbBLqPW1smhcTom3yiAykNj5sgEfw7c
/NkBTWWZjhKUcK6s+V0ue+jfxbPTp+N+ltUTjLW3UpfE7TL/AE628Z30lo8llqyWJiuI3TbGY2VS
HBIbJOMYBHI6c1tkmKpVZ4OjF+9TdS69U2mulum6d+ltSakGm5f10FTwJrsvh/xlF9itrObVZIDa
WqSKFAibcVXHAXnaucdOQtYYfM8LhquETm5KHO5Ss9531d9b9Xv5NlyUp3drbfgXNa8La/rMPjdz
YJavq62TWiPOjb/KGSpI+62ABz8u48MR81PDZjhMLLBrnuqfPzaPTm2fmvxt0T0E4yfN5npUDtJD
HI8TwsygmNyCyEjocEjI9iR718hJKMmk7+ff77M2H1IwoAKACgAoA4DStOk1KXV5Z9c1m2W21Ka3
ijt7sqiopGBgg+tedTpuq5tzas2tGfXYzGQwMKEIUKcuanFtuN3d/d2I7i3soNSttPPibxC1zcEg
Il9nYApOW44Bxx6/nWqwt20py08zgedWV/q1L/wD/gl7+wB/0MXiH/wO/wDsaPqv9+X3h/bf/UNS
/wDAP+CSeA743Hhmye7nnlmcybnaZyT+8b3r8/x2cZjQrShSqWirdE+ndps3zrDUaeOqRhFJaaLR
bLojqlgjZQQ0v/f1v8a8p8SZov8Al7/5LH/I8n2MOxFfNa6fZT3l1LLHBbxtJIxlf5VAyT19BV0u
Ic2qzVOFXVuy92P+Q1Qg3axBol3a6zpkV9bC5jSTcpjlkYPGysVZWAYjIIIPPatMRn2bYao6cq23
ZRs09U17vVGcKdOaukOsrm2u72/tIvtIksJFikLSNglkVxj5umGHpzmlUz/NqcITdXSSbWkeja/l
8i/Y007W6X/P/It/Zk/vS/8Af1v8aw/1lzT/AJ+/+Sx/yD2MOxDZaXZWFsltYw/ZoEztihYoi5OT
gA4HJJrSpxVm9WTnUrtt9Wot/kCoU1sib7Mn96X/AL+t/jWf+suaf8/f/JY/5B7GHYPsyf3pf+/r
f40f6y5p/wA/f/JY/wCQexh2OdbxLbPNBBYaZqt9NM1yojhlRSogkEbkl5VGNxGOc4PQV6azTNkn
KpiYxS5d4/zK62g+m4pUqcXa3W34XNHQr+DVbsQtBe2c0E5iuLa4kIdMxl15VmUgjByrH065Fe3k
ePx1fFOFeqpwcG00klpJLsnpqrNfoYVYxjolZnS/2Zaf3Zf+/wC/+NfZXZhY5H4qwJYeGraa0jne
QanZfu0mJZ8XCHaNzAZJAxkj6iufFzlDD1JRdmk3ftpv1/Jl00nNJrqRSXk0c1wEuGnaKFZBaxyY
lyS/OSwGG24GcDKtye35ys9zFxjepa7tdpW6do9L3e+607+z9Uo3fu/i/wDMJLyaOa4CXDTtFCsg
tY5MS5JfnJYDDbcDOBlW5PYWe5i4xvUtd2u0rdO0el7vfdadz6pRu/d/F/5hJeTRzXAS4adooVkF
rHJiXJL85LAYbbgZwMq3J7Cz3MXGN6lru12lbp2j0vd77rTufVKN37v4v/MJLyaOa4CXDTtFCsgt
Y5MS5JfnJYDDbcDOBlW5PYWe5i4xvUtd2u0rdO0el7vfdadz6pRu/d/F/wCZBHq/m3eow2t291LY
qoktI2Kyq5UsOWYAhgVA6DIbJ9NHnOZxhCUqllK9m1G1tukb6a33e2nc+q0U2uXb1/zJ5LyaOa4C
XDTtFCsgtY5MS5JfnJYDDbcDOBlW5PbNZ7mLjG9S13a7St07R6Xu991p3PqlG7938X/mQT6v5Gpv
ZC7ea5NqbiKzjYiUhSQTuLBcElQM7eQ3J526RznM5UlU9paN7OTUba+XLfTVu1+mndPDUIu1vlr/
AJhqWrf2bDf3U908kVnbCd4ImPmqBvJPLYw23A4HKtyexRznM6zhCNSzk7Xajbp/d6X133Wnevql
HXT8/wDMzU8VXCah9nurDUrfzY18mJpImdnIcgErM2N4QhdwUZVstzgdTzLMHT5oYhOz1dtLad4L
a+tm3ZrQwVKjvyO2n47deprJf3B81t8rSJbpL9hEg89Sd3BO/bzjA6DKt8x7cbzzMNF7XS7XNZW6
f3b6bvrZrTvt9Vo6+78r/wDBHyXk0c1wEuGnaKFZBaxyYlyS/OSwGG24GcDKtye0rPcxcY3qWu7X
aVunaPS93vutO59Uo3fu/i/8wkvJo5rgJcNO0UKyC1jkxLkl+clgMNtwM4GVbk9hZ7mLjG9S13a7
St07R6Xu991p3PqlG7938X/mEl5NHNcBLhp2ihWQWscmJckvzksBhtuBnAyrcnsLPcxcY3qWu7Xa
VunaPS93vutO59Uo3fu/i/8AM6bRbOC502OWfzWkLOCfOcdGIHQ+gr9EwdSdXDU5zerim/VpHj1I
qM5Jd2Xf7MtP7sv/AH/f/Guq7M7HnFpe3D+IvFcH2qScWN4FhtIZSkqr5KEZO8A7jkAtjlT8xH3f
heI6k6OKhye6pLVvVduzei3tfpp39bBJSpu+tjQklkSa4CXU87RQrILWO4YS5JfnJcDDbcDOBlW5
Pb5tYuu4xu7XdrtK3Tsul7vfdad+3khd6BJLIk1wEup52ihWQWsdwwlyS/OS4GG24GcDKtyewsXX
cY3dru12lbp2XS93vutO5yQu9AklkSa4CXU87RQrILWO4YS5JfnJcDDbcDOBlW5PYWLruMbu13a7
St07Lpe733Wnc5IXegSSyJNcBLqedooVkFrHcMJckvzkuBhtuBnAyrcnsLF13GN3a7tdpW6dl0vd
77rTuckLvQJJZEmuAl1PO0UKyC1juGEuSX5yXAw23AzgZVuT2Fi67jG7td2u0rdOy6Xu991p3OSF
3oEksiTXAS6nnaKFZBax3DCXJL85LgYbbgZwMq3J7Cxddxjd2u7XaVunZdL3e+607nJC70CSWRJr
gJdTztFCsgtY7hhLkl+clwMNtwM4GVbk9hYuu4xu7XdrtK3Tsul7vfdadzkhd6BJLIk1wEup52ih
WQWsdwwlyS/OS4GG24GcDKtyewsXXcY3dru12lbp2XS93vutO5yQu9AklkSa4CXU87RQrILWO4YS
5JfnJcDDbcDOBlW5PYWLruMbu13a7St07Lpe733Wnc5IXegSSyJNcBLqedooVkFrHcMJckvzkuBh
tuBnAyrcnsLF13GN3a7tdpW6dl0vd77rTuckLvQJJZEmuAl1PO0UKyC1juGEuSX5yXAw23AzgZVu
T2Fi67jG7td2u0rdOy6Xu991p3OSF3oEksiTXAS6nnaKFZBax3DCXJL85LgYbbgZwMq3J7Cxddxj
d2u7XaVunZdL3e+607nJC70CSWRJrgJdTztFCsgtY7hhLkl+clwMNtwM4GVbk9hYuu4xu7XdrtK3
Tsul7vfdadzkhd6BJLIk1wEup52ihWQWsdwwlyS/OS4GG24GcDKtyewsXXcY3dru12lbp2XS93vu
tO5yQu9DN1PXl029uopHv5/IjtysUMrBmaWRo1wzSAHJA4IGME5OcDqoyxNaEZKSV3LV7e6k9lH/
ADv2XWZqnBu66XGW3iCV9Vlsbi31O2ufs3nw2klwpkkwWzhlmZRngANt6NyedtTddUlUjUTV7N2d
lt0cE9Otr9NF1m8VKzjb7v8AP7vRmrJLIk1wEup52ihWQWsdwwlyS/OS4GG24GcDKtye3GsXXcY3
dru12lbp2XS93vutO+nJC70CSWRJrgJdTztFCsgtY7hhLkl+clwMNtwM4GVbk9hYuu4xu7XdrtK3
Tsul7vfdadzkhd6BJLIk1wEup52ihWQWsdwwlyS/OS4GG24GcDKtyewsXXcY3dru12lbp2XS93vu
tO5yQu9AklkSa4CXU87RQrILWO4YS5JfnJcDDbcDOBlW5PYWLruMbu13a7St07Lpe733Wnc5IXeg
SSyJNcBLqedooVkFrHcMJckvzkuBhtuBnAyrcnsLF13GN3a7tdpW6dl0vd77rTuckLvQJJZEmuAl
1PO0UKyC1juGEuSX5yXAw23AzgZVuT2Fi67jG7td2u0rdOy6Xu991p3OSF3oEksiTXAS6nnaKFZB
ax3DCXJL85LgYbbgZwMq3J7Cxddxjd2u7XaVunZdL3e+607nJC70NDQYkutdmtZ7ySREthJ5AuJB
IhLY3Eh+hwQOByrcnt9Tw9TWMhUlXjezVnsuumiWvfV7rbrw4yXsmlCx0f8AYtj/ANPP/gXL/wDF
V9L/AGbhf5Pz/wAzh9vPv+COS8e7tH1Hw9/Z32pvPuZlkiE7M0oW3lYKN7YByBzke5xmuHMaMMFh
pV6HuyVrPe12k9Nej7M1ozdSahLVMbJeTRzXAS4adooVkFrHJiXJL85LAYbbgZwMq3J7fHrPcxcY
3qWu7XaVunaPS93vutO/ofVKN37v4v8AzCS8mjmuAlw07RQrILWOTEuSX5yWAw23AzgZVuT2FnuY
uMb1LXdrtK3TtHpe733Wnc+qUbv3fxf+YSXk0c1wEuGnaKFZBaxyYlyS/OSwGG24GcDKtyews9zF
xjepa7tdpW6do9L3e+607n1Sjd+7+L/zCS8mjmuAlw07RQrILWOTEuSX5yWAw23AzgZVuT2FnuYu
Mb1LXdrtK3TtHpe733Wnc+qUbv3fxf8AmVYdZabUNUtoJZppNOWMNbo2JGZlLggl8YYEAZC4KtyR
01lnGZRp05yq2U762VtHb+Xpu7X0a07n1WipNcvTz8/PyHz6v5GpvZC7ea5NqbiKzjYiUhSQTuLB
cElQM7eQ3J52qOc5nKkqntLRvZyajbXy5b6at2v007p4ahF2t8tf8yeS8mjmuAlw07RQrILWOTEu
SX5yWAw23AzgZVuT2zWe5i4xvUtd2u0rdO0el7vfdad39Uo3fu/i/wDMg1HZdpd2l2E1GJYUkNgc
M7HLEEhm2kMVAXIABU8+mlHiLNKTjOFZxd2uayS6do30vra+jWnceDoarl+X9Mj1HWzp99HbmaW5
knwsVtC/70NtlfLFnAwwjIXgcqecfdqlnGZ1YOXtLJbtpWteK6R3V7vye3dSw1CGvL2/H5luS8mj
muAlw07RQrILWOTEuSX5yWAw23AzgZVuT2xWe5i4xvUtd2u0rdO0el7vfdad39Uo3fu/i/8AMJLy
aOa4CXDTtFCsgtY5MS5JfnJYDDbcDOBlW5PYWe5i4xvUtd2u0rdO0el7vfdadz6pRu/d/F/5laLW
Hk1HU7aGSaaSwjjJgRsOzMGYYJfGCMAZC4IPJ7avOcyjTpzdWyk3rZW0sv5em7tfRrTuvqtFSa5e
l+vn5+RZkvJo5rgJcNO0UKyC1jkxLkl+clgMNtwM4GVbk9slnuYuMb1LXdrtK3TtHpe733Wnd/VK
N37v4v8AzJrWd5NWW3a83LmHMIdvMUM5BYnd0bGBwOVbk9vTyjN8bicVTp1ZNxbl0VnaN7aJard6
9V88MTh6UKbcVrp37nW/2Zaf3Zf+/wC/+Nfd3Z5Vihr9pDaaRPPbmVJE27W85zjLAdzTQM4vw2Mp
rw/6jNx/7LXJhft/4me9nf8AzDf9eofqaV3p/mXujPFCzKt0zSMq5CjyZBkntzgflXZH4vk/zR4D
+B/L8zc+xxelAHF+BYx/wiOmt3Jk/wDRjV+QZjJ/Wqi9PyR9bn3/ACMKny/9JR29v/qVr56fxHjo
wvGdtfanFZ6Rp4EYu5t9xPJC0kUcUeGKsAy53ttXbkZBb0Nehl86VByr1PsrRJ2bb0utHsru9tHY
mavBx76ffv8Ahp8zndV03W7QapY3ijUrS/lhvpfsVo8aFFdFuItu5uWQBtu7LZcAV6dCvhp+zqQ9
2UU4rmkm7tNwley2el7aaNsiUZ623kvyt+cdFtt31KtpoNteasIoNDmh0aXWllEEtm0cZiFiRkxs
OE38YIHPGM1tPFzp0ryqp1FTaupJu/tO6e9vPbUJJWfKv5f/AEp3/wCD3363dnSNKv4/Gvn3CFLp
L2d5JotLcNLbkN5aPdFwjJgx4QKSCq8DaTWVfEUng+WPw8sbJzWktLtQtzJ3vdt2ab11SHOPvabX
VvJfp1uvnroR+G9Na3n1G3t9MvVjksJkmuksms73eWGFaRm8u4lOWIlXgEZzh6rF11KMJSmrqSsu
ZShbuklzQjteL1ae2hS0rKSWt3/V9mm9uy+ZBZadff8ACN6za6TpsdtCRbEyRaXNZC4UP++Q2zNl
z5Y5K437toPFaVK1P6xSnWnd+9o5xlbT3XzpaK+yd+W1+pnBWuoL7Po76212v59DqPh9ZvZ6feAA
x20lyXghXT3sY4xtXd5cLszKpbceduSWIGCCfIzSqqlSPdLV8ym3q95JJN27X0sm76FQVm2vLpb+
un/D3MXStG1KXWLHbNqGlhG1VmnhhTOHu1ZAfMRlww+YcZIGQcZrvrYmjGjO6jP+Fo2+kGn8LT0e
j7dRzV5O383/ALadfomkppV5G/2m4vLi5uDJNcXBXfIREyjhQqgAAAAADv1JJ9XhbEOvjmuVRSg0
kr2XvRfVt792Y142V2T6/wCFbDW763upy8TI374R8eeoHCk9uccjnGR6EfpByGP8XI0XwdbQRQOY
11GyVYbdvLYjzkAVDldp7A5GPUVyY3TDVHdL3Xvqtuqs7r5P0NKX8SPqQXb7/tkG/wA7FuD9mgfZ
OM7xkNuGN2MKflwVPzen5BBW5ZWtru9V06We3XfRrTv9E+q/4cLt9/2yDf52LcH7NA+ycZ3jIbcM
bsYU/Lgqfm9CCtyytbXd6rp0s9uu+jWncfVf8OF2+/7ZBv8AOxbg/ZoH2TjO8ZDbhjdjCn5cFT83
oQVuWVra7vVdOlnt130a07j6r/hwu33/AGyDf52LcH7NA+ycZ3jIbcMbsYU/Lgqfm9CCtyytbXd6
rp0s9uu+jWncfVf8OcRqunyiXxla6faBbmd7e4KQ2xEk0BC+Z8wZd+7bKAoKnIfn5uPfoVo2ws6k
vdXMtXopa20s7WvHWzVraaa4yX7yfLu0rf8ADle404P4b1G1kSa4tfPWaOwtdJeIIpRgf9GMvmeW
zA4xsIcFhwMjWFa2IhNNKVmnJzT6p/Hy8vMlv8V4+7voZcq5Jrppolb8L/ft992T2FmP7V0uW60j
mKwuYkhtYHSaLdIfLYEtugDqr7AxXYdw3emdWp+6qKFTeUXdtWdlqtFaTTtzWT5tHbuuXa60Tey7
31t0v+B1Hi0S3Oga5aQMs8rae2y2iUmbLK4B4PIbGAMDlW5PbyMDywr0py0XMtXtpb8uuvVbde19
V5f5lR9EeSST7drF/qv2W3EsVjmGKRHZXXfujCHJGQuSACCc5wV2WKUUvZ04wu7OXvNWunazctt3
a91ZW789Om+VKTeltNF/l/w6OXTRTc6PdxXNg8t7a+G7XyImiJkjmxNgqOocEYGORzXrvFclaLjO
0ZVZXd9Gvd38u/QhU1LSSvpLT5v+kL4uiT7VrCahaTXV+8tm1m8MTCSKFmVcednCAsHG0lcncec8
LAyfLSdOSUbT5rtWbSb+G13ZWd9dLLS2uc17sudXfKreWmvprf1Wmux6Fdvv+2Qb/Oxbg/ZoH2Tj
O8ZDbhjdjCn5cFT83p81BW5ZWtru9V06We3XfRrTv3Pqv+HC7ff9sg3+di3B+zQPsnGd4yG3DG7G
FPy4Kn5vQgrcsrW13eq6dLPbrvo1p3H1X/DnU6XBDeaCLa6jWWGQuGRu/wA5/wA5r9cy7/c6P+GP
5I+erfxJer/Mg8M+GrPw+JnhZp7iZjmaTG4JnhB6Dpn1PPoB3GRw9m/ma/42h3+di+3fZoH2T828
YyG3DG7GFPy4Kn5vT4DidWxlKVraLV6rd9LPbrvo1p39fA/wpL/hzWu33/bIN/nYtwfs0D7JxneM
htwxuxhT8uCp+b0+UgrcsrW13eq6dLPbrvo1p3731X/Dhdvv+2Qb/Oxbg/ZoH2TjO8ZDbhjdjCn5
cFT83oQVuWVra7vVdOlnt130a07j6r/hwu33/bIN/nYtwfs0D7JxneMhtwxuxhT8uCp+b0IK3LK1
td3qunSz2676Nadx9V/w4Xb7/tkG/wA7FuD9mgfZOM7xkNuGN2MKflwVPzehBW5ZWtru9V06We3X
fRrTuPqv+HC7ff8AbIN/nYtwfs0D7JxneMhtwxuxhT8uCp+b0IK3LK1td3qunSz2676Nadx9V/w4
Xb7/ALZBv87FuD9mgfZOM7xkNuGN2MKflwVPzehBW5ZWtru9V06We3XfRrTuPqv+HC7ff9sg3+di
3B+zQPsnGd4yG3DG7GFPy4Kn5vQgrcsrW13eq6dLPbrvo1p3H1X/AA4Xb7/tkG/zsW4P2aB9k4zv
GQ24Y3Ywp+XBU/N6EFblla2u71XTpZ7dd9GtO4+q/wCHC7ff9sg3+di3B+zQPsnGd4yG3DG7GFPy
4Kn5vQgrcsrW13eq6dLPbrvo1p3H1X/DnF63pdxPJ4uktoVku3eDYixEztb7I/MCncpZXCOoUFcl
GGc9Pdw+IhBYZSdorm66c13a+jSaund3smnbvjON5z5d7KxXgsLy2s7u50tWmliZlgsbazexZI5k
2EojSF0QyKrZOzBjkI45rWVanOcYVdE95OSmrxd9Wo2b5W110cUzJRsm10s7JW6NPz/LVdyO/wBF
lg1qWwjEkk1uLdrU21m73KwbQGC3AkRYQzLNncRnLEZJFVSxUZUVUeifNe8ko81+sOVuVk42te2m
wp02vdv0XS7v1e6td63e/wArEmoaREdC1RbizllmlvJZpbeCzMszp5s4QyIHVnjYY2YxtYbs4yRN
LEyVem4yslFJNysk+WN7OzSkvtXvdaWvvc4L95ddem9tPwv+p0nhsy/8I/JazW4hKQMVsbYtDMFL
yBWXc+Yw4A2qSuwgjPHy+Vi+X26nF31+J2avZXTsrSs93rzb273S0jJW77adXra+l+iMjxnaXF7q
OrwWsd07tb6dgWnEwH2mQkqTwCACQTwMZPSu7L6kKVOlKTSV6m+3wLf/AC6hXTd0v5f1NtNIMd/d
TXeqXmrzQ2hWK3LRRTRB924qY9gBfYArHGCrYbk44HibwjGFNQTlq9Wna1r35tr3aV73WhXJrrJu
3TT9LfL5mpdvv+2Qb/Oxbg/ZoH2TjO8ZDbhjdjCn5cFT83pxwVuWVra7vVdOlnt130a076Pqv+HC
7ff9sg3+di3B+zQPsnGd4yG3DG7GFPy4Kn5vQgrcsrW13eq6dLPbrvo1p3H1X/Dhdvv+2Qb/ADsW
4P2aB9k4zvGQ24Y3Ywp+XBU/N6EFblla2u71XTpZ7dd9GtO4+q/4cLt9/wBsg3+di3B+zQPsnGd4
yG3DG7GFPy4Kn5vQgrcsrW13eq6dLPbrvo1p3H1X/Dhdvv8AtkG/zsW4P2aB9k4zvGQ24Y3Ywp+X
BU/N6EFblla2u71XTpZ7dd9GtO4+q/4cLt9/2yDf52LcH7NA+ycZ3jIbcMbsYU/Lgqfm9CCtyytb
Xd6rp0s9uu+jWncfVf8ADhdvv+2Qb/Oxbg/ZoH2TjO8ZDbhjdjCn5cFT83oQVuWVra7vVdOlnt13
0a07j6r/AIc1fDk3/FQSxefEdtqG8kD94mX+8eehxgcDlW5Pb7XhKPuVXZ7rXp109V116rbr5mYP
WK9SxfeEdMvddj1OVTtGWktwP3cr8YY/rkdCcZ75+1PMMX4pfPf+Gl8uWXN1cDZC+yRv9Em4Vsja
T2ORg9x1rxs80wE3dLWO+q+Jbqzuvk/Q6cL/ABV8/wAhl2+/7ZBv87FuD9mgfZOM7xkNuGN2MKfl
wVPzen5dBW5ZWtru9V06We3XfRrTv7r6r/hwu33/AGyDf52LcH7NA+ycZ3jIbcMbsYU/Lgqfm9CC
tyytbXd6rp0s9uu+jWncfVf8OF2+/wC2Qb/Oxbg/ZoH2TjO8ZDbhjdjCn5cFT83oQVuWVra7vVdO
lnt130a07j6r/hzI8bRy3ej3trFm7jVYXnsrfIuHh8w+YAQwzuVSAOM7WGTnA7cucadaE37r1tJ/
CnbTp0bu991ous1OZxlGL1t/w/3q6RyOoW0H2bXLS00SWTTp7qGRLMWUwaNPIP7zyVZGKsyFVHyh
WBJPHHtUpy5qM51UppNX5o6vm25mmk0ndvVtaW115ZKNpKEdLLTbq+mnX0u9dtRdB01oNTtftemO
7RW96kcVvaNFNBvlLREHcTErKHCEsAp3DdzwsTXUqcuSe7g227p2Vn095p25tG3p7vdRik1daJ7J
W3Xrom/Sz3t0u+ErK4hv547lZDex2Li/htbN7WSd2Pys07SASOSsm2RcD73K8VhjqsJU04/C5Llb
kpJJb2io6JJrmi/LRlxi+fXfXZdHtre3p2201Oh8apNdaRe2sObpFWF57K2yLh4fMPmAEMD8yqQB
xnawyc4Hm5c406sZy03tJ/CnbTp0bu991ouvRU5nGSi9f+Dr96ul5/hg6hp2nakbex07SbhdNW68
yWxjha2cg28ylgpZfLRyAgyEBYNyd2a9GlWq0b1KlRc9rKV1JfFF2uk7tbuzk7W0VjnnGMouMFpd
abf5f11M/VNOuvsCWc1us2nWxvAdP/s+S5kTdNIIWEaOpAKKyo3AXB55BXpo1oc7qRdpvk97mUVp
Fc2rTTabTktW+2mqqQa5ora+1ulu19r7dnr6aLWsKXUcHiSzvNYePS4BbqtuZJopMuGJ2s3lOxC4
csB8p+f5TjlVSTi5YaShecr62TWlt0uZLX3bPf4dQ5UklNXVtreb6avayTfbp1NcspJtb1WW4tbi
+sYmgkm02EESyq0RUSLhhuKsOOcAqxzlRgw1VRo04xkoyfMlJ7KzvZ6aXW/XVLZu7rR5r6aJK66t
Xlp8t/O3odndvv8AtkG/zsW4P2aB9k4zvGQ24Y3Ywp+XBU/N6eFBW5ZWtru9V06We3XfRrTv1Pqv
+HLNpL/xN0i8+JtjQN5IH7xMufmPPQ4wOByrcnt7PD8bY6k7PeWvT4dvVddeq2682Mf7qS9PzNrx
P4ctPEEcfnO8E0bDE0YG4pnlfyzj0PPqD+onhDtZtrex8MSWlnEsMEQVURe3zD8z796aEzipfC+r
6X9pNn4kfy7idp3D2UbMzN1JPAzwOgA9AK4lh6kW3Cdk3fY+ilmuDqwpxr4bmcIqN+drReSRW+2a
pbXAtJPGLRyblU40pWRWboGf7qk8YBI6j1pqlXeiqfgiHjssSu8H/wCVJf5Gl9k8R/8AQ3f+U2L/
ABo9lX/5+fgg+vZZ/wBAf/lSX+RW03w6dO0WNW8UahbW9t5hYpHbLHGoZiT88bEDucse/bivNnkm
Bd51o3fV3a/BM5cdj547EyrRVua2m/RLeyNOVLKz0Wy1Obxxr/2W9j8y38mzt5XkTbu3BFti2AvJ
OOB1xWc+G8sjPllSs/8AFLTzetkvN6HDGrOWz8vn2Xc1m8PMlgb5vG+rraCLzjOVsdgTGd2fs+MY
5zSnw3ldO/NStbzl/mEK0525Xe+xkQS6dNaXNwPHPiKJbUI0kc9hBFLhzhCsbWodtx4XaDk8DJpv
hrLF/wAuutt5Xv2tcFWn36X+Xe5oaPpA1i3eaw8Z+IGETmORJbW1hkjYAHayPbBlOCDyBwQehofD
OWJJ+y3/AL0v8xe2ne1yrDFZy6v/AGXH451/7SZGhUm0thE8ijLIsptdjOMHKhiRg8cGlHhvK5K6
pefxS2va++o5VZw3f9Pb0uFpBbXZu/K8Z+JEisxI01xNYQRQAISHIle1CNgg9Cehpf6uZUoc7paa
fal120vcftKnNyJ6kmiWcGtvLHp/jTxF5sKqzxT2VtBIFbO1tslqpKnBwwGDg88Vf+rOWJX9l1t8
Ut/vJ9vK9r/15Fi80ZbG+srG68cazHdX7sltEY7MtIVUs2ALfoAOSeOnqKlcNZY20qWyv8UtvvG6
s1Hmvp/mXP8AhEbz/ob9c/792X/yPR/q3lf/AD6/8ml/mHtp9xkvgy6k27vF+vAqcgqtmpBxjqIP
c12YPKcHgajqYeHK2rbt6fNvsTKcpKzG/wDCFXf/AEOniT/vu1/+MV6t2Z2MDx14JlOhRLceLPEF
wkmoWUW15Lddu+6iTcpWIEMN2QQeoHUcVMkpxcZK6Y1o7o0tX8GwWel3M+o+Mtdt7VIz5sg+yoVX
GOCsG4H0xznGOa8VZFl1NqXsuq6yevTS+vp1Or61WenN+X9IpafoNhrrXFhB4v8AE8Uwi3PDPaRW
c2w5G5Q9sjYzxuXoe4NVDIMvi+dU9n3b+9X/AD0evmS8ZV+Hm/D+v+Boak/gBp4ZIn8Wa+FkUqSn
2RGAIxwwgBB9wcilHIcvjJSVPbzb/BsbxdZq3ME/gBp4ZIn8Wa+FkUqSn2RGAIxwwgBB9wciiOQ5
fGSkqe3m3+DYPF1mrcwT+AGnhkifxZr4WRSpKfZEYAjHDCAEH3ByKI5Dl8ZKSp7ebf4Ng8XWatzB
P4AaeGSJ/FmvhZFKkp9kRgCMcMIAQfcHIojkOXxkpKnt5t/g2DxdZq3ME/w/aeCSF/FmvhZFKkp9
kRgD6MIAQfcHNEchy+ElJUtvNv8ABuw3i623N+Rg6P8ADXStRjln07xx4wmSKWW2ctfjAdSUcYaP
qDnn8Qehrr/s3BSipexjZ6rRd/8AgGTrVE3Hmd15/M3p/ADTwyRP4s18LIpUlPsiMARjhhACD7g5
Fckchy+MlJU9vNv8GzR4us1bmCfwA08MkT+LNfCyKVJT7IjAEY4YQAg+4ORRHIcvjJSVPbzb/BsH
i6zVuYzb74QaffXUlzceJfEXmSkM4jmgjVmAwrFViA3DAw2MjAIPArrp5bhaUVCMFZfP1V3rZ9Vs
9e7InXqT+JmlP4AaeGSJ/FmvhZFKkp9kRgCMcMIAQfcHIrkjkOXxkpKnt5t/g2W8XWatzBP4AaeG
SJ/FmvhZFKkp9kRgCMcMIAQfcHIojkOXxkpKnt5t/g2DxdZq3MSp4HuI12x+MfESLknarWoH5eRX
r04RpQVOGiSsvRHPJ8zbYv8AwhV3/wBDp4k/77tf/jFaXZNihF8N0zqKr4p8QIbyUtO6tbB2Yxqu
7d5OVOFHIx0z15rz8RluFxVVVa0LyXr67bP5m0K06ceWLsihqek6TBfPpF5428RRyyFYXaOCAJE0
g+VWmW22xucjALBuVx1FclLIcv5k40tb93a61tq7P0NZ4qtGN3LT5bbX8vU2J/ADTwyRP4s18LIp
UlPsiMARjhhACD7g5FEchy+MlJU9vNv8GxPF1mrcwT+AGnhkifxZr4WRSpKfZEYAjHDCAEH3ByKI
5Dl8ZKSp7ebf4Ng8XWatzBP4AaeGSJ/FmvhZFKkp9kRgCMcMIAQfcHIojkOXxkpKnt5t/g2DxdZq
3ME/gBp4ZIn8Wa+FkUqSn2RGAIxwwgBB9wciiOQ5fGSkqe3m3+DYPF1mrcwT+AGnhkifxZr4WRSp
KfZEYAjHDCAEH3ByKI5Dl8ZKSp7ebf4Ng8XWatzBP4AaeGSJ/FmvhZFKkp9kRgCMcMIAQfcHIojk
OXxkpKnt5t/g2DxdZq3ME/gBp4ZIn8Wa+FkUqSn2RGAIxwwgBB9wciiOQ5fGSkqe3m3+DYPF1mrc
wT+AGnhkifxZr4WRSpKfZEYAjHDCAEH3ByKI5Dl8ZKSp7ebf4Ng8XWatzBP4AaeGSJ/FmvhZFKkp
9kRgCMcMIAQfcHIojkOXxkpKnt5t/g2DxdZq3ME/gBp4ZIn8Wa+FkUqSn2RGAIxwwgBB9wciiOQ5
fGSkqe3m3+DYPF1mrcwT+AGnhkifxZr4WRSpKfZEYAjHDCAEH3ByKI5Dl8ZKSp7ebf4Ng8XWatzB
P4AaeGSJ/FmvhZFKkp9kRgCMcMIAQfcHIojkOXxkpKnt5t/g2DxdZq3MU9Q+FkV/MJZ/GHipGVdo
EF3FAuP91IgM++M1vSyjA0VyxpL5q/53Jliast5fp+RLB8NVgsGs08XeJTEyspZ5rd5OeuJDCWB5
4OeO2KiWS4CU/aOkr/NL7lp+GoLE1UrcxPP4AaeGSJ/FmvhZFKkp9kRgCMcMIAQfcHIrOOQ5fGSk
qe3m3+DZTxdZq3ME/gBp4ZIn8Wa+FkUqSn2RGAIxwwgBB9wciiOQ5fGSkqe3m3+DYPF1mrcwT+AG
nhkifxZr4WRSpKfZEYAjHDCAEH3ByKI5Dl8ZKSp7ebf4Ng8XWatzBP4AaeGSJ/FmvhZFKkp9kRgC
McMIAQfcHIojkOXxkpKnt5t/g2DxdZq3ME/gBp4ZIn8Wa+FkUqSn2RGAIxwwgBB9wciiOQ5fGSkq
e3m3+DYPF1mrcwT+AGnhkifxZr4WRSpKfZEYAjHDCAEH3ByKI5Dl8ZKSp7ebf4Ng8XWatzBP4Aae
GSJ/FmvhZFKkp9kRgCMcMIAQfcHIojkOXxkpKnt5t/g2DxdZq3ME/gBp4ZIn8Wa+FkUqSn2RGAIx
wwgBB9wciiOQ5fGSkqe3m3+DYPF1mrcxIPAsytuTxdr6MBjKC0U4/CD2rtweAw+C5vYRte19W9vV
vuZ1Ks6tud7Dv+EKu/8AodPEn/fdr/8AGK7rsxsUdU+HIv3tftnizxHIYnYxt5lurRlo3UlSIQQd
rEZ989QDWNalCvD2dRXWmno7lRk4O8SLXvC1rptgW1Lxh4ijjnPkqsEVu0rswPyosduXLYyfl5GC
eMZryY5Fl0Zq1LX1k9tdr7d76HT9arNP3vyM+7sdFfSop28beJJIb0SIiWtrE0/y8SfJHbeYhU8E
4BU4zg4oWRZdTal7PZc27at3etreoLFV5XV+tvO/bvf/AIcvTeG9OuLG3c+ONa+zajGxhliNqoZN
hYsHWD5QFBO7IxxznFU8hy+jJ3p6x11btZW87Nar1EsXWmtJb6fP/Mpx6bpWp6VdzW3jDxVNDFtj
lWCxQTgOPlZUW18zBByHUY7g8UlkOX02pey695PVa2av+D7ruH1uq7rm6eW22j6/IWDS9K1TTNSm
Txl4njt7LMV0ZLOK2kiJUHADWyvuwwI288jHanHIMvi4yVPd2Wret7bX76a6fiDxdbWLlsr/ACHH
SdJvdQfRh428RCeVntwywQRozgHciTC2ClwM8K24YPQg4VPIcvupRpba7vo+zeqv6oJYuslrL+nt
6BbeHtK8RyXOmWnjfxG7xjc3lLDbllDFS0cgt13qGGCUJHY9aqjkeXxtUhSXzbe+2jez6O2vQJYu
snyuXft03+a69UR6L8PNJupNQTTPHXiq5a2d7O5zfpII32gsoLRkBgGHK8g9wQa3nleClGM3Sjbd
aJbenT10ZHtqsZcvM7/5mhp3hWz8QaU1xpvjXXLizmMkQmh+ypnaxRtrCAHqDhgfcHvXPHIMvg1L
2XZ6t+q0b/BmksVWu4uW2j2C58K2cmpf2HJ411wX09s83kx/ZVkEQIUvuWDK8sADkHOcdDhQyHL0
+aNL4bdW/Td26bfeEsVWSV5b6dAXwrZ399faPF411x7q2iQ3McX2VXiWQHb8ywDaSASMHI4PGRRD
IcvXvxpbPu3qvJvX8gliqysnLf0KniHR9K0otZ6r418RRGSEvIYIIWMMZ+Xe7x2x8peuHYqODg8H
BTyLLlNctPVNbt2u9k7u2vZg8VX5b37/AIb+ehDrGnaVZyNZX/i3xdEJmWASx6avls0mAoWZLXbk
lgAVbr3zTp5Bl6mrUtb9W+nk35ddLeQpYuqot82lr6W2+Rqav4Xh0iy+133i7xCkSuir5NvbSOXL
AKFVLcsTkjoK0w+UYLC1Y1KULS1tq30d+va4p4irUi1J6fL+tytd2VrZ2Nrd3PjbxfGt2xWGE2ie
e5AJP7n7N5nABJ+Xgc16spcrs+1/l+m/6HOldXL9r4R/tTT4ri38beILm0uEWRG3WpV1PIP+oq5K
UXZkqzWhqTQrKuGFAHG6hNo95rUmkC9sbOKKZGui8yJJPKMFUUZyei5b/gI74UPeaa6PT1/4f735
bk/dVu6/D/hvuR1f9nx0wJItBsL3RSl9bRXMaSSOElQMu4O2Dg+lc9fSEn1Sf5GlPdLucrpGoWeh
6Z4J1XWJ47XTxoMkBmlOEErJA4XJ7ssb49cYroxXx1oLdrTzs3dLz1WnX5Cim1p0m/8A27X08/Pz
N7RbrT9D+G1lD4lMKLZ6Skl3azgMwjCgEFD15+XHrxRiJqM297Nff0+9rRhD94247ScmvS9/yepT
8NeItHuHv/E2oa1p3nSRRQtBZ3Kzrp9vuOzzSmQG3MSzn5R0zhSxlx5ItX1b1fS+tkm/na+7fmkT
fmd0tEnZdel3b7tOi+Zc8B3FvF/a0x1KO/t7rUQLbUnkTN8TEg4K4RipDINgA+TGMgkvaEYtWeun
zbv81r6arSwSa5209LL5dLfk/V9zNsNe0LxB4litbTU9LtLLSrqRrazinQXF3dAMGfylOdg3OQMZ
dvm6Abs46w9pHs+W2tla1/u2XRebsqmuWXJ5q/re9vvtd99O5U0HV9L0jTfs0mvx+INCttNlk1IS
wxAWjKU2qYwoZS+6TKSFmyvbBzbkoxbtouXlfnskntppZ9NLsduaTS0bbuvLVtvr/wAO9DY8G6xp
mqXd94hudZ0trqWKOM21texyLZQBiUVypxvLMcnpnCjOMlqPImt22rvpfZJfp1bb8ks+ZNroknb0
6t/cvRfMs+JtPs4vF3hm/jtYVvJr9kknCDzGUWs+FLdcD06UqWk5JdYv84lz1ptvpy/mdZSEFABQ
Bz/jz/kB23/YV03/ANLYKAJfGy2beGrpdRivJLXKF2shmWDDgiUf7hAfgH7vQ9KltJp3tZ79vXy6
PprrpcpX1sr6PTv5f18tTidQ1W6uLbWE0PXrfxOI9Juni1C1SP7XYvtXahlhwh3kEhQqt8o+9jIp
PlXNJWScdejXNqn3su2lt1qrunZzir3u9vlv5dte++jRJqnib+0brVp9H1h5tLW204T3FrOSsETT
Sid1YfdIQfMw5UDOQV4rlSa59ud/+kq2vZy07b6mUW/Zx5dZcr+/T8UrtL001s7N9f6Umn2S2HiK
9k8OPqRS9vzqEpWJfKJVFus7thkC5becMdu4fdEr4o821pW6Xd+vyvbvZbldHyb6X62XV+u1+yd7
LcqeJtSWKw0ZLDV3k0GRbn/T77V5rAPIGHlj7SqFnG0vtzkOFyS2OZfNzdnyq3+dravbTzena42t
7uuuvXT16K/Xo9NNiDxHq15Z2+k3Oqau0l5/ZsT/AGWC9n0+WWXPLwIU23LtwPKdRjAyBvxWyS9u
0l1j8u+nbz7X100zt+63/m179te66d73230Na1P7J4/jRtSmnlkubdI7KLUJYJ4UYANi1KmOePqz
SdVG4A5QVFFXlbzl+XVdPJre6fXUqP8AdqW2i/Pp3fS3l56dP4It0tdLu445YpM6leOfKlWQDdO5
AyDwcEZB5B4NC/hwS6JFT/iSfp/6SjfpCCgAoAKACgAoAKAI4f8AWTf7/wD7KKAOe8QaeL/VrPSI
Rb21nds17flCgluPLMYVcZyQSV3Pg4ChcjcKIL3rvaNmvW7a+56+b9GmSXuPvLT5W1/DTyR0tABQ
AUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUARzf6yH/f/wDZTQBz/jrxDp3h
y0tLi7Fkb2WbyrE3kqxRpIVILtI33FC5yRzg4AJIBm/vcsXZtP7tL+vTTq7bbqklytvZfn0/4for
nMSeIdD8P6bY2+na7olxq+qGeQ6tPcRiCLc+6Z9277u7AWMHkgAngsKcYv8AdR0ikvW1397b5vJa
+jlXs6ktXfbzsvuSSV+r06sfd6ZDfeHtTsfDsov7TTdBe0s5I5BKZ5JV3Mdw6kqkfTrvNEpKKdSS
sk46doxs/mmmv/AepdJ2qQTfdt+bbV/Kz5vS/wB13SNesLjVNc8R6VNHc6baaPbq0sZ+TzE86Qpn
+8qsuR1G7FFVyp06jWru7eei273el+tvIijHmdKk9Glr5Xsv0en+ZNZae0GieHNGbBnvp1vr5j1Z
l/fSNz1zKUH0atJRUKqhHaCdvl7q+d3zeqZCk503N7yf3X1t6cqcfuKNlreh+JPEkVlZanpVnaaZ
dSm1s47mNJ7u6wwZ/LByEG5yOMs3zdAN3Py89Pmjq3FqPkrWv92y6LfXbWfuS5X3V/W97ffu++nc
g8DyW2o3fhywhKyS6Ros1pqcQ628hMKeW/oxMcnB7LmuiTjUdSa+GSjb8X+C3XS9nuKTcHbrzN/L
XX53Vu+5teE9I03zfFWlfYLYad/aKp9lESiLb9mg+Xb0x7dKj4qUObXf8JMJe7U0/lX6lv4cRpF4
ckjiRUjTUL1VVRgKBdS4AFNtuEG/5Y/khSSVSaXf9EQPp9nZfEywmtLWGGW6068kndEAaVvMt+WP
UnHHNKnoppbe7+LkOprGL8//AG1kekWGnaZ408QQ28MNjanTbWSUxfugCXuSzlhjB7ls575qVZUJ
J6JN+Vlyx+4cr88Gt3f5u6M/xhr+hC9bw5Hqul6a19aJ9v1C6ukRxanIVUZjmSRgWwTkKCWPUBhp
TlKM9k9Vtd9rdOl32sl5JNwjGUd+j7Lv/kur3NiaKG+8ZaXZR7WtNJsjeIoOQZHPlxN74US4+tWn
J1Kk5bqy+crt/PRfJvuRZKnCMdn+UbW/O/yRD4w/sr7PZyTeIzpMEGpGSS6LCZUlCONheTckWCQR
uGMgADJFZq3Mnfvb8nr96tva9rW00fwyVu3y2a0+S8ur3Odur+6kudI1fVdfOkWKwX1vFq5SH96P
OTymyymMGSOPdkLhsHbjIpyfIpX0k4xdvNXuu/VO2/3MLXso6pPX7v0d1fb1bud54UvLzUPDWm3m
pII7ue3R5VCFOSOu08rnrg9K1qLlla1vLs+q+T0MoO63vvr3V9H81qUdtz/z1i/79H/4qkMqyX8U
d8ljJqVkl3IMpA2BIw9Qu7J6H8qFrsD03LW25/56xf8Afo//ABVAGho4lGnA+ZGAHkzlD/fb3qJN
LVlJCXes2Flp0WoXmr6db2M23y7mWRUifcMjDFsHI6U2rS5evYEt7dC9+927vNixjOdhx/Ok2lqw
WuxnWniDS7yxuL6z1zS7i0tc+fPFMrRxYGTuYNheOeaHorvYLa8vUs6dfQ6paLd6ZqFneWz5CzW5
EiNg4OGDEdabTW4kyKPV7GTVX0qPVtPfUY13PaLIpmUYByU3ZAwR270lrdroN+7a/UZZ65p19ez2
VlrWm3N3bZ86CGVXkiwcHcobIweOaLrl5+ncGrPle4/StWstYieXSNW0+/jjba72rrKFb0JVjg07
aXDZ26hPq9jb6nFpk+rafFfzjdFavIqyyDnlULZPQ9B2NJauyB+6rsvbZ/8AnpH/AN8H/GgA2z/8
9I/++D/jQAbZ/wDnpH/3wf8AGgDn/HYm/sS2y6f8hXTv4D/z+we9AG7NI1vC809xDFFGpZ3dcKoH
JJJbgUm1FXY0m3ZFPSNZsNaSR9G1jTtQWIgSG1kWUIT0ztY4qrO1ybq9i/tn/wCekf8A3wf8aQw2
z/8APSP/AL4P+NABtn/56R/98H/GgA2z/wDPSP8A74P+NABtn/56R/8AfB/xoAhtblbtGe0u7adE
do2aIbgrKcMpw3UHgjtQtk+jDZ2Jts//AD0j/wC+D/jQAbZ/+ekf/fB/xoANs/8Az0j/AO+D/jQA
bZ/+ekf/AHwf8aADbP8A89I/++D/AI0AG2f/AJ6R/wDfB/xoANs//PSP/vg/40ARxCbfLh0+/wA/
If7o96AKs+r2NvqcWmT6tp8V/ON0Vq8irLIOeVQtk9D0HY0LV2QP3Vdl7bP/AM9I/wDvg/40AG2f
/npH/wB8H/GgA2z/APPSP/vg/wCNABtn/wCekf8A3wf8aADbP/z0j/74P+NABtn/AOekf/fB/wAa
ADbP/wA9I/8Avg/40AG2f/npH/3wf8aADbP/AM9I/wDvg/40AG2f/npH/wB8H/GgA2z/APPSP/vg
/wCNABtn/wCekf8A3wf8aADbP/z0j/74P+NABtn/AOekf/fB/wAaADbP/wA9I/8Avg/40AG2f/np
H/3wf8aADbP/AM9I/wDvg/40AG2f/npH/wB8H/GgA2z/APPSP/vg/wCNABtn/wCekf8A3wf8aADb
P/z0j/74P+NABtn/AOekf/fB/wAaADbP/wA9I/8Avg/40AG2f/npH/3wf8aAI5RNviy6ff4+Q/3T
70ARahfQ6XaPd6lf2lnbR43TTkRouTgZYsAOaTaW40m9itda/pdnp0Oo3WuaXBY3GBFcyTKsUmRk
bWLYPAPSm/ddnuJaq6LhuAvkg3duPPOIsj/WHBb5fm54BPHYU2rNp9BJ3V1sUR4j0g6fNqA1/STZ
QSeVLcidPKjfj5WbfgHkcH1FK6ST77efoVZ3a7DrDXtM1G0nutP1vTLu2tv9dNBMrpFxn5mDYHHr
Ts9CetiSPWLGXVH0uLVtPfUI13PaLIpmUYByU3ZAwR27iktb26Delr9R9nqdrfXVza2Wp2NzcWjB
biKJg7wk5wHAbKng9fSharmWwPR2ZNDN5zypDdW8jwNslVBkxtgHDDdwcEHB7EUdLhtoFvN9pjMl
tdW8yBmQtGNwDKSGGQ3UEEEdiKA2dgabbcpbNdW6zupdIiPmZQQCQN2SAWGT7j1oQbAs265e2W6t
zPGqu8QHzKrZAJG7IB2nB9j6UeYbFbUdXsdLmt4dS1bT7KW5bbAlxIsbSngYUFhk8jp6ihavlW4P
Rcz2K114p0OzvzYXfiPR7e8Vgpt5bhFkDHoNpfOTkfnRH3tI6hL3d9C9qF9Dpdo93qV/aWdtHjdN
ORGi5OBliwA5pNpbjSb2KsviDSodLj1SXXNLj06U7Uu2mUQueeA+7B6Hv2NN+60n1Etb26GjG0ks
ayRTwujgMrKuQwPQg5ptNOzEmmroyKoRzniVImjjktWtmjS/g+2RRoPNeTem35geCMqSCCSMDI60
Q0nHtrb1s7/8H+kEvhkutvw/rY6OgAm0y21bw3LaXvmm3ZpS6RytH5g3N8rFSCVPcdD0ORxXPX+B
vtr+BrTeqX9bnJ+HRbC28DjUPLFn/wAI7NjzcbN3lwZ/Hy9/4bvet8Xbmr37fhd3/Hlv8iYqyjy7
87/9ut+pu+G0tZPhXp6a+dtk2lILoyOV/deWM5I5Hy1WJspty7/j+uvTrsFP4mqW13a3a7tb5bEW
k2tteXtx4g1i1t9PtLxLe1srW7RQSqOWidwejl3G1Oq4HRiQJtKN19tu/ezSf3u122vTZXcXi7W+
GKt6p2v8u3zfUs+Bop4b7xHHfNHLdjUQZp4YzHFKTBERtQk7cLgEFmJIznnAI29lG397/wBKf4f1
ru6n/Eb8l+uj/rZrZaFKCztdT1qBNGtlt9L0W+mu5rxjnz7ohw6ITk4BkYu/TI2jODtzXux9otEo
tR9O78vzfvdE25K75Orab8tmvnt6LTrpT0Z30/RrfRfEt5pt/pF/pc91LcWYkRFQFDIWl3nzFfzS
dwCdOhzxclFJxkvg5f8AJK3V6fPsNXcuan1k/wAbu9/L8L7m34VtZrvVrrxFLaHT4bq3itrW2ZQr
mFCzLJIP4WO84X+EAZ5JAdnBSUt27vy6ff3foul3no2uXaKsvO/6aafN9SjrNjbaxrFzouk2oBe7
gvNWvjyImTYyIueshCKMDhFOTyQGmno4y6Rba831X46vt7q62qps11krei7/AJ2XfX17SgAoAKAO
f8ef8gO2/wCwrpv/AKWwUAO8dx2U3he6h1K9+wQSNGv2kx71jfeuwuOhTdt3ZwMZyQOaWvPG291b
1Wv/AA3na2th6csr7Wd/Rqz/AA9TmPEeo6to0+pT30WnyavFo11LZanYBkIjTYxWSBywA3HIYsw4
PC5ILi0m1trG/Zrma36Ozf4u+mlQjzSgnqm3bvt+K7+dtNmWvEHiXULfVNQtbK9SOLydORJQqMLY
3E0iPLz1O0LjORnHGM5pRvLlenvtfdFO3q3p8zJStTjPd8rf4pX9Fq35J+pY1C61G0lsdFi8SvPJ
d6gbeW+8qD7RbKITKIyAvl72K8EoPlPQn5qmPvyS8pP1ae3yvr6dCpe4m/T5X6+mll5vd7FTXdW1
mF9M0nTNSvNSkkS6aW+06OzEpaJlUIwmIi43/PtwSV4CjOJcnq10in5Pz729O++17sorXvbzWl/v
7X6d3qVtW8R64lhZanNem1gi0yK7u10w2twIXJJZ5VdtzQkD5fJbccPyeDW1kqrXS8Uu2vR9U9fT
rbvFnyWW/verts+2nVeaRf1XWtStPFW+TUZ10sXdvbKLVLaWBDIFGydSROsjMwwUyoDISPvVFJXd
n1cvTRN6W6q2t/TroptcnNHok/x3t2a7a7/PZ8EWEmnaXdxTRPE0mpXkoDrglWncqffIwQfQ0LSn
CPZIqf8AEk+9v/SUb9IQUAFABQAUAFABQBHD/rJv9/8A9lFAHMeJNFW7votNsbLYup3K3t/esrNs
8ny9oU9A5wgXkYAYjkckNJLoou/q2/65vL3dnoT1g+7935a/l0/vO/c6ugAoAKACgAoAKACgAoAK
ACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKAI5v9ZD/v/wDspoAyPFdxYWUVld3lq97dw3H/ABL7
aM/PLOVZQFGQPuluW4UZJxjNJXUvdXvWf3dfRd38le9m7LlfNouv6euuy7+hz8Nivh22tENjFqHi
a+a6e3to2Ihh85w8vPQRqdoLkZPAAy22hwTj7GD0sk35XetvV6R66LZXQm9astNb2W97WXzstX01
fXWjrGkzaf4bvdKtHeb/AIR/w9LGsqrtLzSIR8oHQhYzx2EgpzlGV5y+G8Y69lZyv6rlu+tmXRTV
SEerbl83dK3ldyXyRq6XdWVh4k1i8svL/s+30WzlfycbPl84r+Plhfwx7UVZunCrKW6k/v5Vf9DG
jFTjRit2vw0t+PNb5kVlYyL4d0iynXffa/dpeX7nnt5zg/7ICLEPYqK0cPZ1I0ukLv5rr6ubTFzc
8JVP5tF6Pp8oX+frq+Kxg1XWIYtDtfI07Rr2a6lvDyZ7tg4eNC2SQDIxZumQFHQ7cHdU+ePSLUV3
vpf07d373RN6ytzcj6tN+VrNfP8AKOnXTM8FJDLL4Rjtm2yvoE63bRHDgl4clj2PmeZ753e9byUX
Koo/DaNrdteW3yvYTdtXvzy/Xm/Hlv8AI1fBui2cDeLNKtzcQ2x1MZZLmQSndbwMx83O/cSTls55
PNQ0pUYJ7a/hJhL3an/bq/Ut/DG2hsvCptbWMRQQX97HGg6KouZAB+VU5OUYN/yx/JCkrVZ+v6Ih
bTLaz+KdneRea1xd6Zdea8krPwJYNqqCcKoyeBgck9STU0tI1Ir+6/8A0odTWMX5/wDtr/pjPD+k
2+nePPEUVm86Pc2FpJJM8plkLlrgbsvnoAAB0AAAGOKUF+5cFpaT/wDSY/j6jm/ehJ+f5rT0DxXa
wXtxc6Jp9v8AatY1WxW2u7qXlba1yw8xx93OWfaigbm9ACQuVTulpG6bt36Jeemn8u+71E3TSlu9
UvPvfy799vS1qNst94n0fRnZntNOg+3yqx/1jqQkO71wd7/VFParUuarOp2/OV/ySa+Zny8lONNd
fyjb8219zJPFdje3B0y3tNVtIZm1ETr9vG4MFR2CIiFC+CA2CwOFJJOKiKfOmuif46fdZ2+7dlu3
JK/W35p/p/wxzkt9q+s+IdHlQ6db3FtDqMInuoHeBpI5UjLogcHLKrYG/wCUM3LYOU2lGU+8U7Ps
73Xpflu/TTXRtWcYf3unfluvza9V02Ow8G3kd/4V0u7htIbKOa2R1ggGI4wR0XgfL6cdMVtUXvdf
nvts/NbMzj1v3e3rv89ypuuf+eUX/fw//E0gKrWETXy3zabZG8QYW4OPMAxjAbbnuaFpewPXctbr
n/nlF/38P/xNAGho/mnTgPLjILyZBc/329qiST0ZS0G3miafe6fDp97o2m3NlBjyreWJXjjwMDap
XAwOBind83N17gm1dLqS3mm218si3um2NyssflOJVDh0znacryM846VLSe/l+G33dAWlrdP1Kdp4
W0SyguILPw5o9vDdJsnjit0RZV9GAT5h7Gm9VZ7AtHdFq10qzs7SC0tNKsILa3fzIYYkCpE2Sdyq
FwDknkepptttN9P8rflp6Ctuu5UtfCuh2d8t9aeG9GgvEYutxHbIsgY9SGCZzyaUfcVo6Dl725JF
4c0iGK8ii0DSY477/j6RYEAuOSfnGz5uSeuetKy5VDoug7u/N1G2PhnRdOSZLDw9pFqk4AlWG3RB
IAcjdhOcHnmqv/n81t9xNv69dxs3hXQ57838/hvRpbwuJDcPbIZC46NuKZz70o+58Og5e9ozY3T/
APPOP/vs/wCFABun/wCecf8A32f8KADdP/zzj/77P+FAHP8Ajszf2JbZjQf8TXTv4z/z+we1AG7K
jzRPFLBDJG4KsrNkMD1BGORSaUlZjTad0UdM0HTNIimj0rRNMsY5xiVbaJYhJ1+8FUZ6nr603rHl
ewlo+ZbiWnh/S7K0mtbPQ9Lt7adPLlhihVEkXn5WULgj5m4PqfWh6qz2BaO6BdA0tdJOlLoeljTS
cmzEK+STnOdm3HXnp1oetr9AXu3sLc6Dpl1psOm3WiaZNYQEGK1kiVoo8AgbUK4GAT0Heh7qXVAv
dVkOvtGsL+e2nv8AR9OuprQ5t5Jo1doTkH5CV+XoOnoKadpcy3Fb3eXoLLo9jNqkeqTaTp8moRLt
ju2jUzIOeA+3IHJ79zSXu3t1G9dGWLW2WzRktLO2gR3aRliO0FmOWY4XqTyT3oWiS6IOtybdP/zz
j/77P+FABun/AOecf/fZ/wAKADdP/wA84/8Avs/4UAG6f/nnH/32f8KADdP/AM84/wDvs/4UAG6f
/nnH/wB9n/CgA3T/APPOP/vs/wCFAEcRm3y4jT7/AD85/uj2oARoN1yly1rbmeNSiSk/MqkgkA7c
gEqMj2HpQtAJd0//ADzj/wC+z/hQAbp/+ecf/fZ/woAN0/8Azzj/AO+z/hQAbp/+ecf/AH2f8KAD
dP8A884/++z/AIUAG6f/AJ5x/wDfZ/woAN0//POP/vs/4UAG6f8A55x/99n/AAoAN0//ADzj/wC+
z/hQAbp/+ecf/fZ/woAN0/8Azzj/AO+z/hQAbp/+ecf/AH2f8KADdP8A884/++z/AIUAG6f/AJ5x
/wDfZ/woAN0//POP/vs/4UAG6f8A55x/99n/AAoAN0//ADzj/wC+z/hQAbp/+ecf/fZ/woAN0/8A
zzj/AO+z/hQAbp/+ecf/AH2f8KADdP8A884/++z/AIUAG6f/AJ5x/wDfZ/woAN0//POP/vs/4UAG
6f8A55x/99n/AAoAjlM2+LMaD5+PnP8AdPtQBU1bRrDWY449Y0jTtQSIlkW6jWUKfUBlOKVle47u
1ilJ4O8OyQxQyeFtDeKEERo1pGVTJycDZxk88U+t/wCv61FtoaVhYQabD5OnafZ2kWANkAEa8AAc
BewAH0FD1VmJK2xDZ6Jp9hYzWNjo+nW1pcbjNbwxqkcmRg7lC4ORwc0PVJdirtS5uvct+R+9jl+y
2/mRKVjbPKA4yAdvAOB+Qp9bkpWVuhmWvhXQ7O+W+tPDejQXiMXW4jtkWQMepDBM55NKPuK0dBy9
7cuWWl2mn3Nzc2Gl2NrPdtvuJYUCNM3Jy5C5Y8nk+poWi5VsD1d3uTwweQ8rw2tvG8zb5WQ4MjYA
y3y8nAAyewFGysHmFvB9ljMdta28KFmcrGdo3MSWOAvUkkk9yaPIOtwaDdcpcta25njUokpPzKpI
JAO3IBKjI9h6ULQBr2iPJNI9las88YilY8mRBnCsdvI+ZuD6n1pNJpxezHdpp9jNvvCmhahMJr/w
3o11KqBA81tG7BQMAZKdAOgp9W+r3FskuiNOO2WKYzRWdskpjWLevDbFyVXO3oMnA9zTu9fMSVkl
2K95o9je2ktpeaTp9xbTSebJDLGro7/3ipXBPvU2Wnl/X6v7yrvXzEu9F0+802LTrzR9OuLGHaI7
aWNWiTaMLhCuBgdOKcvefM9WJe6rIuoJY0VEhiVVGAocgAenSm227sSVlZGRVCOM1TW7K48XaYp1
O2jSzvGg8kzKGLmJwzMOo+YhR759RRS96V11Tt96/F/la27HU0g16P8Ar0X5+R2dAgmspNQ8Ny20
V9c2Idpd8tsVEhXc2VBIO3PqOR2IPNc9f4G+346GtPdW/rU4/R9PtNZ0vwVpOrwpc6c2gPOYJeUa
RUgVWIPUqrvj0JzXRivjrT6paeV73a7PRa9PmTH3Urfzv/27R/10On8MGTV/hvp32+9nhe601BLd
JJskXKcuGPQ45z+NGJUeZ8227/Nr06egqa5JOMOjaXXZtL1Mjwv4e0jUpNTm03TI7Xw1eQxQxWyA
wx3rIzEzbVxlGBVckfOAc5UjMtSUXzLVu6T6aW1XS+9ulk7XvZac1k9k033v+dtdfNroaHw6g+xH
XLE2sFg1vf4+xWpzbW4aKNgIjgcEHcflX5mbjuXe9OLvff8AN6ei6fpsiStUfov8r+ulvkt9zPj0
ewfxpA2hQtNf2N1Jc6pqjAbyGVsWpcY3H5kwnRFRc4O3MQvCPNHZJr/E/wDgPVvvoutqqa6PdtP/
AAr/AIK0t1u2/Ov4Z0xbBDpuuaRaaLqur2VxNLqdlOhuT8ymXzJPLGwgyAjDOOOowMvlgqbhfSKj
fs0tLvbe2vq7Mbvz861vJ2763a/BfloaXgLTrKPU7/UvD9imnaFPDHDbxxx+Wt06libgL0wQyqGx
lguem0m1zKL5urul26fK/bokuraWbtzK2tlZvv8A5211832IvHej21tfWOtQ2EAma/thcal5hN1A
vmoipECOEbO1gGUYZjtYk1NL3asUut/m2no/Lbv8t1c/epy7pfgtbrzWr6evQ7ikIKACgDn/AB5/
yA7b/sK6b/6WwUATeNbZr3w1dWcd7BZSXGyKN532JIxYYiJHOH+5xz83GTxUtXcVa+u3e2rX3f8A
B0uUnZN7aPXt0v8AL5epx0lxH4PfVLiDw5B4f1CPTJ5oYbKRH0698sK24hVRvMUtjlV4LYLcY0g7
+6n1jdPpd2uvvV/loEYJyjdfNel7P7m1v111aNzXPFV9Y6neWNtDbs4isVtmkVsLLcSyRkvg8qu0
HAwTyM85CUXJ2X8zXyUeZ/Pf8DNSSpxm+1/xSX4vUmvtR8Q2AsNOll0t9R1C7aGG7W3kEKxrGZCz
Rb87vlKhRJg8Nn+GkvekorTRt/JpK33r013Kfupt+SXq/wDhn+XmVPEXiTWtH/s7Tn+zDU7mOeV5
4NOubyIrGVAxFEd67t6kkkhcEZbINK+rstktO7fS+y2er8tNykrK76u367fhb56bEOreLdatrfT7
1rNNIs5rNLiY3tjPMFkJ+eJ3jx9nCjHzyKR83T5SK0UV7VwvpdJed/Pa/S3frrpGvs7rfX8NtN7P
X0Rc1LxFqtl4qjtJhbWmnPNDFCZrOd1uQ4ALC5QmONtxKhHXLEDkbgRNP3nZ766eiv8AP8LfLUnp
BSj2X5/grW1219S18PrY2uj3qkYL6rfN/wCTEn+FEdKVOPaK/wAyp/xZv0/9JR0lIQUAFABQAUAF
ABQBHD/rJv8Af/8AZRQBxXivQrKbxDarawGfXtQuFuI76Rhv0+CEpv2MBkLyBsH3mkOeM0UlyyXL
0d2+9+nzWnZJN77lTWDv10S897/Le++y227mgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAK
ACgAoAKACgAoAKAI5v8AWQ/7/wD7KaAMXxrBo8mlxTeIS0ljbzBzabQ63bkFUjMeD5mWIIUdWC+l
S7KSdrvov662vrsld+apXs1ey6vy/wAvz262fKtoem6f4bsR4k05r12kn/s7QMLKqmVtyRhDkbo0
GN2dqAvjA5pzi7KmneVrX/W/RLRX3aS6uzUXvP4Y3v8A0vN3fL3eu10mrx6jpnhw2r3TS33h3QJZ
3nRmO24dCiMCeSVVJeTzyD3qptVJNt6Nxjfa92uZ+T+F+V9B0YrmhG27bt2tsvNatf8Abpc03RtC
0/V9Y0ptPtH0QaZa3s1tJEskRkDSgyFSCCxWNST1JUHrSqSUac5SWkZO3l7qul29PN9yKaclTs9Z
Kz89rX+bev8AkVtE0W1sfCNpa29lBaXHim8SWeG3jWNEjYeY0e1RgBYUK+5OerVpyuE4Un9jV+q1
v6c1l6WFdSUqkeui6aPRfO15ff8AKcaPYnxhE+gQtLqFhcyXOp6o4yxDK2LUuMbj8yYToioucHbn
nu6cHOOyi1/iffzs1dvvouqVySbUXu2n/hX6XWiXW7b86ngi2S3u/DlzZEQ3et6JNPqE6gFp5QYW
Ej/3mDSuAT2OOldEoKLqU46JKNvxV/V7t9bXYS355LVSa+WunorK3Y1vBumzwt4ssY9VvDOdTGb2
TY82TbwEtgrsHU4G3aOOMDFQ1zUYJab/APpT/MJaVNdfdX6/1+Zb+GMAtfCptxJLKIr+9TfK5Z2x
cyDLHuT3NU3eMH/dj+SFJWqz9f0RC1jJb/FOzuZb65uTcaZdbYpCojgUSwYVFAHryTknjnAAE0tI
1F/h/wDbh1Phi/P/ANtf9fkM8P2FxZePPEStqE93cTWFpIJbkAhCWuAFCLtAUYHA5PJJJJNKF1Rc
VupPX/t2Or/pDnbmg3tr+a/q5W8faTYX0ggmhGp+Ib218iwjK/LZEE7rle8QDMpL5z8qKCTgFJXk
1T0d079ktvydl1d76J2L8sU56ra3d/11+ytd9zXPC+j6p4u0ezn0uwluo1/tC+vPsqedN5e1Y1L4
3fM5BPPIjx0NXBpVZTirJa285Xt9yUn62Zm0/ZKEtW9PkrX/AEXo2afjXTNT1SwtbOOxs9Vhe/WS
aCciGLyVDMqyEhy3zhAcKc56AZrNL3ot9L/ql+D+9dDT7MrPtb71f9fk7anLXflazeaNpNj4Z06a
0tYb4vpMkoisxPFKkTHhDuA3Pt/d9XBIU9HL3lKb1XLG3ezvt56JeSvrrZprktDa71+5NX9b3fmt
nud54SubW78M6bPYQywWz26eXFM5d4xjG0sSckdM5Na1HeV73vrfvfUiKsrWta6+52KXnSf8+0v5
r/jSAhnjS4lglms5We2cyRHco2sVK5+9zwx60LR3DpYm86T/AJ9pfzX/ABoA0NJYtpoUwSEM8meV
/vt71E4qSaZUXbVFK98L6ReaVZaZNp1wtrYJ5duIrl4njXbs271cMQV4IJ575py96XNLV/59Gtmt
FoNPl273+ffyZZv9Gsb/AE+XT7myn+xy2/2VoI5zGnl/3QFcAemRzjjpSkuZty8n9zv/AF36ih+7
SUdLf1/XboVI/CulpZy2j2+pzwy7fluNTnmKFTlWQvKSjAgEMuDwOabd/wCtfv8Az79RJJaLbby+
4u2Gk2un2ywWtveKqy+cXa6d5JH9XdnLPxgYYkYAHQChvby/r9fv13C25R07wppWm3Jns7fVI8yP
K0R1OdoWZySxMZlKHJJPIqUkoqPRK2uunzKbblzddxqeDtESxubIaddtbXMJt2je9lYJEesceZP3
SnA+VNowAOwpvVWfk/PTa73fz8+7BPld15/iWdP0Cz0+KWK3GrFJQqkS6pPLtAORtLynb+GM9DTu
/wAb/wBfqtn1Jslt6f1/WnQH8PaY+rHUjY3AuGkWV1W5ZYXkAADtEH2MwwMMVJ+VeeBhR93b+r72
7X8u77scve3NfzX/AOeEn5r/AI0AHmv/AM8JPzX/ABoAPNf/AJ4Sfmv+NAHP+O5G/sS2/cuP+Jrp
3df+f2D3oA19RtbfU7GWyv7E3FtMu1432kEfn+vak0mNOxnWnhnSrZbhTZXdz9phNvI17eSXTGM/
eQGWRiqnuBgHAz0FEkpRcXs/6/Dp26Cj7slJbrYit/COiwW11brptzIl3HHFK093JK7KhJTDvIWB
UsSCCCOMdBim29+9/n3v3Be7t5r5Pp6eX+bH/wDCK6R9gaz+wXZVphcGY3khuPNAwH87zPM3bflz
u+7x04pdvK/47/f1BO1/P+v689RZPC+kvYW9kLC6hjt2Zo5IbuSKbLffJlVw7bictljuPJyaGk2v
S3y7W2sNNq/3/P8Ar8NNht74U0S98kTaVKiQwrbiOGdoY3iX7sbojhZEHPysCOTxyarmfNz9b3+f
f18/8hdLev47676klx4b0q41UajLp05n3pKVFwyxO6fddog+xmGBhipI2rzwMKL5dvP8d7dr+Qmr
q3Tb5djTtYxaoyRRXJDOznzJjIck5OCzEgegHA6ACktEl2H1uTea/wDzwk/Nf8aADzX/AOeEn5r/
AI0AHmv/AM8JPzX/ABoAPNf/AJ4Sfmv+NAB5r/8APCT81/xoAPNf/nhJ+a/40AHmv/zwk/Nf8aAI
4pGDy/uXPz+q8fKPegBGXNyk5huA6KUAEuFwSCcruwTwMEjI5x1NC0Al81/+eEn5r/jQAea//PCT
81/xoAPNf/nhJ+a/40AHmv8A88JPzX/GgA81/wDnhJ+a/wCNAB5r/wDPCT81/wAaADzX/wCeEn5r
/jQAea//ADwk/Nf8aADzX/54Sfmv+NAB5r/88JPzX/GgA81/+eEn5r/jQAea/wDzwk/Nf8aADzX/
AOeEn5r/AI0AHmv/AM8JPzX/ABoAPNf/AJ4Sfmv+NAB5r/8APCT81/xoAPNf/nhJ+a/40AHmv/zw
k/Nf8aADzX/54Sfmv+NAB5r/APPCT81/xoAPNf8A54Sfmv8AjQAea/8Azwk/Nf8AGgA81/8AnhJ+
a/40AHmv/wA8JPzX/GgCOWRt8X7lxh/VeflPvQBn67ollrv2b+0ba8LWkhlhaC7e3ZGIK5BjdTnB
I/E0re9zddvvHfTl6FKbwfpM720kkWsGa1R0imGsXIkVWILDeJtxBIHU9h6U9nden5/5i6W+f6Gl
ZaZaWcM0UdpPIs6hZftE5nMgC7QGLsSePXrz60pJSi4vZ/5W/JAtGmt1/m3+bZU0/wAMaTp2m3mn
2un3At72Pyp/MuXkdk27Au9nLBQvAAIA7Ypy99Wl6+r8+/z9BxfJJSjo1+nlt1NH7LCJraUWkge1
QpD84wgIAPG7B4A5P9TTbbk5Pd/53/MlJKKitl/lb9TL0zwrpml3f2ixh1SJvNeYx/2pO0RdiSxM
ZlKHJJPI60o+4lFbJWHL3m2+pPpHh/TNGvJ7vTtOmimnBBLTl1RSxYqis5EaliTtUAZ7cCiPux5V
tp+G33dO3QHq+Z+f47/fbXuXbS1gs57ua2s5EkvJRNOd4O99qpnluPlVRx6ULRKPRfq7g9XcNOtY
NNt2gsrOSKJpJJSu8H5nYux5buzE/jR0S7afcD1bfcHtYH1KHUHs5DdQRPDHJvHyo5UsMbsclF/K
haXt1t+F/wDMHqkhpsbf7Zc3gtJluLqFYJZFl2kopYqBhuCN7cjB59hSt7rj0f8Alb9B31T7GZee
FNLu9Qa/kh1WO6aJIWkg1S4hLIudoOyUZxknnuSe9PZt93cXRLsakVnBFftfJaS/aWhWAyNJuJRS
SBy3qx56nvTvv5i6Jdv1t/kitqOi2WpQiO7tbxtkxnjkS7dJInIIJR1cMgwSMKQMEjGDU2ta39X1
+f8Aw3ZDvuv60/r+rsiufDml3OnW9i9jcpFbZMbw3TxSgtncfNVw5LZO7J+Y8nNEkpO77W+Xa3bR
abaIcW47evz7mlZxR2NpDaWlmYbeBBHHGm0KigYAHPpVyk5Nye7JilFWRmUxHM3M5TxHcT6hBqaW
kUsMMMyTtHApIHJUON+WcLnaw4570U/xbf5bfg38wn+n+f6HTUALLFqE3hySPSruKyuGeUee8Xm+
Wu5slVyBu9M8DqQehwrNqLfb+vkaU90cvpj3eu6X4R0u61K/iS60R7yeaC5eKaWRVhVSZFIbrKzE
Z5IGc1tiVyzqyjpyrTtd31t1tbZ6a+go+6l195r5K/8AwNux0nh26v8AXfANhcC7FtqF7YIftIjD
bJGT7+3gHnnHSnXiuZpaL9O36XFBezbjvZta+Ta1/UxtAsDfXmr2ml6tq8mhqkcP2g3zySPcKzea
IpHJYLt2qSpABzt2kEiL3g5NaXul3Vvyvtrrq72eo/dly9bNP16fPe+nbqaHw/mnaPV7ec3ka2t8
Y4rW+nM89spjRtryFm3ZLFh8zYDAZ4wK3pxfr+b/ABX9X3akrVGvJf8ADr/LuntsUZILi18Y2cVp
q99fakZ5LnUI/Of7PDaEOEQw5KKc7AuAHbazZxuqIPlTe6Sd/OW6t5+S2jo91eqmq7NtW9Fvfytf
X+a1rdK/hNrq4t3huv7b0jXtTtZZopr+dpohlgSY4DKyp5e9BhlQ/Xmnye5yX25b9/Np62vr6dgb
tNy3V3bt1sradF+G+po+C1xrepjS769vdFiRIRLd3UlxuulLCXy2ck7QNoODt3AgDIaqi7wbezd1
6W1+V9r+b2aJkrSS6pa+vT573t5Eetarez+NNChsrhotOivnt5whwLiX7PKxU4PKpheP7x9VpUve
k29rO3yaTf33S9H3RU9IO2+l/m1Zfdq/JrzOypCCgAoA5/x5/wAgO2/7Cum/+lsFAFvxZFqU/h28
j0Rit6yDZtcIzDI3KrHhWK5AY9CQalrVX2ur97df6/FblLr3s7ettPx8n6M5G31qHw6+qXCLrlrL
aafLcPpGrzSTef5e1hJFcM8i4w21grHqMgEc6R1Vt9YrzV3b5p/dpvqxRhzSS2vf0f8Ak/ubV9Gr
Nb2seLRp17d2a2XnTRRWpgHnbRNJcSPGqE4+UApktzwTxxgpJt2W/Nb7lzN/df7iU1yRm9mr/krf
NsW68QatZw2ttc6Lbrq15dG3t4BfZgkAQuZPN2bgoUEcx53DGMHdSWrSXZt+Vnb8br79dh7Jt7aW
9X/T+XnoU/EHjaTQraxj1G00+x1K7WVzDfamsEAWMgHbNtO4tuUqNoJBOduCKTkk/RJvv6JdXv1t
pvqilHS772/ry/X7yK8+IManS3srS28jUbWO6ia+vltGmDnHlw5UrJIO6llHzLzzkaKH7x030aXn
r1t2/HyvvF7U+f19Fbz89behcuvFzweLhoYtbRfnjQCe+WG4mDLkvDCy4kRehIcHKuACRzFP37/P
8FfVdn03/Ozn7sU/63tb16/NFjwG91JpV415cSzv/ad4qtI5fCrO6qoz0AAwB2oirUqfflX46jnp
Ul8v/SUdDQIKACgAoAKACgAoAjh/1k3+/wD+yigDjvFNpdw6xBJa6pqEmrXt0n2G3hldIIIE2+b5
kYbY64LEswzl1VcHbRT0kku936bfLTRW15tdr2J/A38l3v0/4PTlXfftaACgAoAKACgAoAKACgAo
AKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAjm/1kP8Av/8AspoAyvFcEUunLLe6rLpmnWzedePF
K0LSRhT8vmKQyDdgkqcnGO5qW1F8z2/V7evkurt6FRTekd/6v/w/RX9Vy0cMi+FYL7xJq+rWumxP
Mbe3S4lju51d8WwZ0YSM+3gIcklhuyRTnGSSi/jslZfza/Ju1rvZWb21FBptuPw3vd9vzSve3Vqy
8majqmuab4dhN3cONU0nRJb67+YEGYoViD44bkSHGMEpmrn703Z78sdNryau16W07KSuOjFNxTvZ
tvXey6Pz1X3MuaZYLb6rqmhXmpanPYCxtr0yyahMsqOWkVyJQwZVPlqdoIUc4GDipk4qEpPRRf4W
/G2u93r5IiHNJQfWS19Vbbte/TsVdEiurfwjG632oCfxHeJ9lSa8lme2gc5Cq0jFgRCrOTn72fQA
XZxlCnLday9Vq16bQ/4LC6fPOO2y/wDSU/m3zehPPDc2fi20js9Xvb7UvOkudQjM7i3htCr7EMRJ
RTnYFIAZtrNnG6sVJwi2tVGLv5y3Vu2vRbR0e6vUley2bat6db91a+v81reVfwhc6gt1odyb+5uZ
tf0iW8nS5mZ4kmBiZSik4RR5pXauAQB3Ga2lDkc6S+ylZvvqnf10dtl0sDs3zv8Ama+WtvmuXfzd
7ml4TOuMPE1tcarHdahDqOyKaaFvJiBghbCxBshRuOF3ZPc5JNS1elHl031/7ef9LsEtJ69l+v8A
TLfw6kvH8M41G9lvrmO8u4nuJfvPtuJFHHQDAGAOAOBTdnGDS3ivyFLSpNef6Ig3atF8SrZLrUQ9
jPp9y0VnEhRE2yQgMxyd7/MeeABwB1JVP4Z330/9u/y17jqfDFrv+n9WG6C+sx+M9fg1C/S9Isra
W3gVTFDDlpxtAyx52jLck+gAACjf2L6tN/kn8l94525o9Fr+a+9lfx5BOsBuX1S9h1CeEW+lWFjc
PFm7OTuO0gSj7ud67VVSSOTSs1K0NW3pfZJb3Xbv8ktbXE1y3n8K3tvd9n37Lvq/JuuaQ134l0e0
ivtSgvZ/9Lvng1O5WMRRbQVWMPsG92Ufd6bu/NXGyqtx+Fa6+d+Vfm/lbZmbv7JKXxPT/N/p6tMv
+NZNTewtbaCyvpRPfqki6XOyymBQz58zMfl7ioU/MB82MnNZrWUb+d/xS7d0/k1qafZlbyt96v8A
r+ehz+o6ml3No+l6dD4hms1hu5Z7W1vWF2ZYpFjKPO0oOFZnz+8wSFALDALlrzSeySat53183pa1
nu3Z2ulblSj1b6+l/le6fSy002O38N3MF3oFhcWl1PdwyQIUnuBiVxjq/A+b14HNaVPie3y2+XqR
Hb/P8vkZ32mP+7L/AN+m/wAKAMy40+G4uzLLd6g0BkWVrRkJiLLgg8puHIBwGAyOnJyR913/AK/r
1/yB6mn9pj/uy/8Afpv8KAL+lSI+mbCJAGaQcRt3dvas5xU04vqVF8rTMq48KWT6Tpdja32qWL6X
B9mgurcKJjGUCMrbkKnICn7oOVBGMVU/3knKXXRro1+f4337ji+X77/PX/N7l260a3l0RtHtbq/s
LI2gtES2QAxKBjcrFCQ2OM5I9s80ql6rbl1/r7n18trCpv2drdP6v69fXe5VsvDptNLOnrr+tGFF
RbfZFDCbbYQV2eXCoI4AKsGUjgjGaqUnJ3e/9fL+tLMUUoqy2/r53/plzS9Lj06N9l7fTXE04nub
mSJPMuCFCgMBGFA2hR8oX7o75JV9ktl+v/B1/wCBoH9f1+P3soaN4Z/si7nmg17WZIrmd7ieCSGD
bK7dcuIQ/HAGG4AAHAxUxVoKD1SVv+DpbW+vqVJ3lz9f8umvQa/hSCW2niuda1u4d7Z7WCeTZ5tr
G+NwRxHkk7VBZ9zcdc5JJLmi0+tr+dultrd0l19AjLlkmumvz7/LoW9G0aTSbL7HFreqTQpGkcKv
bW6iBV6BAkKjpxznjpirlJyd3ve/9ev39rEKKirL+vP1/p3IL7wZ4XvdWtdTk0S1S7t7g3JkSxQN
M5Vh852Zblt3XO4A9qmH7t3j/W2vroVL301L+v6/I6Lz09JP+/bf4UAHnp6Sf9+2/wAKADz09JP+
/bf4UAc/47mU6JbYD/8AIV07/lm3/P7B7UAaWtWNlrWnSWV6k/lsVZWjV0eN1IZXVgMhgQCD7Umt
mnZr+v66PqNO109mZZ8L2tylwNZ1HU9Yae2ktQ10iL5UbjDhRFGgycDkgnjgjmhq6dtH366ar8df
uveyCLcZJ9v6/r592Qp4PsjHdG71PV7y4uY4E+0zBRJEYXZ4mTZGqhgzZ5BBxyDzm23utHe/ztb0
tbS2xKSSUeiVvk7f5XT3v10VrEnhyKW0jWbWNZkvYrj7TFftt82J9uzCr5flhdpIK7MHJJGeanaz
Wlr/ADv3/D0srD7p/wBW/r9NhZvDsTw2hi1bWIb61EgGoAK87rIQXU742TaSFOAoA2jbgcUW107W
9f1v576saffvf0/paf8AB1G6x4ZttUtltJdT1mKza3FtcW6uXW5jHZzIrMCQSCyFWOeTwMUn7/N5
p281t/w234iTaVlvrr6/h+Gg/UPDttf6ilxcahqptVmiuDYdYDJGQUblC64KqdqsFJHIOTlRfK7+
tvK6s/ze9xNLl5ForW+Rq2EUdlE8avNIHleXLQBcFmLEfKoHU9Tye5J5pLRJdhvdss+enpJ/37b/
AAoAPPT0k/79t/hQAeenpJ/37b/CgA89PST/AL9t/hQAeenpJ/37b/CgA89PST/v23+FAB56ekn/
AH7b/CgCOKZQ8vD8v/zzb+6PagCJ4YH1KG+PmeZDE8QHkDoxUn5tu4fdHAIB7g4GBaX87fhf/MHs
kWfPT0k/79t/hQAeenpJ/wB+2/woAPPT0k/79t/hQAeenpJ/37b/AAoAPPT0k/79t/hQAeenpJ/3
7b/CgA89PST/AL9t/hQAeenpJ/37b/CgA89PST/v23+FAB56ekn/AH7b/CgA89PST/v23+FAB56e
kn/ftv8ACgA89PST/v23+FAB56ekn/ftv8KADz09JP8Av23+FAB56ekn/ftv8KADz09JP+/bf4UA
Hnp6Sf8Aftv8KADz09JP+/bf4UAHnp6Sf9+2/wAKADz09JP+/bf4UAHnp6Sf9+2/woAPPT0k/wC/
bf4UAHnp6Sf9+2/woAjlmXfFw/D/APPNv7p9qAMrxNosPiBLNXv9Qsvsc4uE+zRIQzj7pYSRuDg8
jjg4PUCkk1JST2v+P9W+bHf3XHuUb3wu95dWF3N4k1z7VYCQRTfZ7YnL8Fipg27sfKCADgkdzlrR
trtb8b/5X9EJ6x5X3uaMGj2iwXsd9Ldagb+JYbh7iIBpEClcfIigA5Y8Dqx6UpRUouG19fnZK/4I
cW4yU1uv82/1Kdh4YtLTT9RtpdQ1S8l1C3FtJdXABmSJVKqqlUC8bmOSCSWJJNOovaRcZdXd+d7X
/BW0sEH7OSlHpsu39ffsaYsLRZtPkAnA09GSFPLO0ZULk/LnIGQMY+8apybm5vd/q0/zSIUVGCgt
lb8E1+pl6L4b/se9mnt9e1iSO4uHuZoJYICsrt13MIQ5A4A+bgADoMVMVaCg9Ulb+vnr6lS96Tls
3/ViTQPDVjol79pgub+4EcTQWsU65S0iZtxSPCA4yF+8WOFUZwKabUbemvXTb8/V9bhL3nf1fze7
/ra7saOnWVtp91qFxCbhn1CcXEodDhWEaJheOmEHXPOaFpFR7X/Ft/qD1d/JL7g0ayttIs2trY3D
I08s5MiEndJIzsOAOMsce1HRLskvu0B6ycu4S2VtLrVtqrG4E9vBJbooQ7SrsjEkYznMYxz60L3b
+dvwv/mD1SXZ3/Cw0WFumq3mpRSXUdzd28duxEeQgQuVKgr1zIeuRwOPVa8riurv+CX6Dvqm+n6m
ZfeGjc62NXh1/WbS7FutsDFBAwCA5OA8LbSx5OMZwPQYFo5W6/1b0/zYnqop9P6v6mpFY28esNqZ
e5kuGtltvmQ7QqsWzgKOSTz24HApqy5rdbfhey/Fi6JPpf8AG3+RHqNg97CFTVtVtJUmMsc1uqqy
AgjZtKFGXBPDqx75yARNrW/r+vlrp5u77r+v6/rsUZPDFmLW3SzvdRsbuAyn7dAi+dIZTul3boyh
3Nhj8owQMYxRJX0Wita3l/wO+++uru0++ut/nt+Wnaxr6VbWmlabbafZxyrb20axxhkYnAGOTjk+
9XKXM77EpWRQpiOWm1l5PEFxCdVexitriOBIha745CQrHzHx8pbdtX5l5HfpSp62fdvT0v8Ajpf0
toE/d07L8/0/4Op1NMBZJdSi8Ou2jRW0l3vlCG5kKxp87fMcAk4/ujGemR1GFaTjFtGkEm9Tn7LV
da1rSvDFnBqj2N5qOktf3F5HDGzsyrEAArKVALS5PHRcDGc1tiFyTqOO0Ondu9r9baPaz21FHRe9
1k18lf8AHRd+p0GjanqGteCbTUrJLePUbyyWWMS58pZWXvjnbn8cUVoWk4xdl+n+dvxFD3Xaetm1
620+V/wMjTH1uXUtX0iDxDNdx20MO7UZLWFnt5iT5kShFVSdgVgCp2lhncDipunFy2Sendrr9z0v
bXVboNVJLq1t0T6P566X6X6l7wJqV1qNtqK3N3PeR2t4YYZbqEQXBXYjHzYwq7TljjKqSu045ya+
xGXV3/Nr7+/6bJPSbj6f16f8Hfcpz3Wuaf4m05LjVluHvrmXzNMiijMUFoobEobaJAQRGCWYqWcg
DpiItR+LpFtvs+lvyV9Wrvoyp7XWmqS8+/4a6baLXrV8I61fazp89za6zdTand20k9rZ39oILWMF
soUYQq0iqCgYhm6+4p8klBLrpd9V3stPO2mtlqDsqjvsm1ps7N21110/PTSxp+F7nUV8Q6nps+qy
6za2kURa5liiQxXB3b4sxqoOF2NjGRuGSciqVnFu3XTzXX7n173XQl3UkuttV27ffrp5X6lSTXDN
43urSbWdQsbWzlgt0hhtFa3lkZQxEszRME3b0UDepJ6ckVNLVN+bt6Jfne/4DqLlsvK/nu/wsl07
nZ0AFABQBz/jz/kB23/YV03/ANLYKALfiy41G08O3k+jRNLeIgKBE3uBkbmVf4mC5IXuQB3qXuls
rq/kuv8AXzs9il172dvW2nbr5r1RzWmeJo7BtTuX8Q3Gr2en2jz3VpfWyW2oQMuCCIvLi+RlPVgO
cYJBONFqvVpJrzdrP9Ou/kSouUlFbvv+a/J9PSzvval4psdOnu4JYrl5bWKCQJGgJlMzskaJz94s
uOcAZBzjOJs9l3t+F/ut+TBNcqlsmr/d/wAPoMl8UiGzjebRtUivZbj7NFYMkfnSPt35Vt/lldoJ
3b8DBGc8UdUl1u/S3f8ArW6sG176f8H+v12EufFSQW1qU0fVJr25WRxp6xxrOixnDsdzhcAlRkMd
24bcg5pNpelrt9l59b+Vr6PsNLvprb5/ltr/AMHQZL4ysmlt002xv9USa1S8Z7SND5ULkhXKsys2
cN8qKzcdOmbUXzOL6NK/S72/4fbz3JvaKl66ddLX+ev3k7eJYv7cl0yDTdQuRbyJFcXUKI0UDuoZ
Qw3b+jKSwQqM8kYOJh72vTVfdv8A07fihy91L0v8m7foJ4Kvb6+0y7l1KUyyJqF3Ch2BdsaTOijj
rgL1oj/Dg3u0m/mOWlSSW2lvuTN2gQUAFABQAUAFABQBHD/rJv8Af/8AZRQByfia41zTtQjuYtXC
NPeRQWGlRQo63KceZ5hK7w2PMbKsFUKCc85KfxRT1u3fyXf5b67v3eqCfwNrSy+99vnt+Pp2FABQ
AUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUARzf6yH/f/wDZTQBQ8QQ6jPbw
x6dqC6bH5m66ugFMkcQUn5A6smSduSwIAz3xUuyd5OyV/wCvTqxrsld/1/S/pPl7G91q/wDDceoX
fiH+zNMt/tDvqawxCa5jV8QybXRowrLliQBn5doANE+aMFJq0rLT+959e3u73bXQI2cnGOqvv5W1
8tHdX2sr63uLdeKNYtPDtle3UYivbfSJtSvYGj27mVAERhyUyzE4zn5CPWtJr35Rjp8K72cn+KVp
LzCklLlV929e8V19XeP3lrS/7YbUNQ0K/wDEF00i2lvex30UMCSR7y6ugBjKbcx5GVJwxyTgGlLl
UZPbldvVWvr577W6eZMW2oy/mW3Zq233re5V0bUNZHhSS9l1e4updVvEi0t7iKHfHC7BVc+WiqxK
7pORwMDsSWv+XcZKzer+7ma9eVW9bg9HNrZafPa/pzP7tSxc3euab4j09bjVRdSXtxKZNMiijMUN
oqtiUNtEgIIjBJYqWcgDpjNS5U762i2/J9Leuyvq1d9GVJaaaapLz73+Wumi0WvWDwtrWszXWlzX
t39tTXdMkvo7Yoka2zqUIRGABKlZQCWLHK574rRwcOeG7ilr3eqfyva3VLe4OzfNsuZr87P10d+9
9LF7wxqfiG5j8QrfxWc9/Z33lW9vHKUhjUwxOE8zZuON5JYrk84A4FS1+6i47u//AKU0D0nZ6Kyf
5/n+Bb8BX+o6j4dE2szRTXq3VzFI0SbU+Sd0AUegCgDPPHPNU7Wi11Sf3oT0nJdn+iIF1LWh8QYN
PuRbQaVLYzyRRxtvkkZJIhvckDbw5AUZ7knoAqesZ33Vvud/zt8hz0UWu/6X/rv5DdD1TXJPFet2
uqxQLDb2tvNa2lswcgM0wOXYLlm2DjhRwMnlio/wnJrW7/JOy+/d2CStKKWzv+a1/wCAQ+NbnWrO
yuNTt9VOlwwW6/ZLWOKOWS6umJxFIGU5BOxQI2BJLc9KTvF6au6sujXXz7+iV+9nGzWuitq+36af
i9F5s1xdbOuaRb2GvX9rcX7iae1Eds0NvBGFMuMxFzklVHzcF89BirikqrS1irv/ACXz/JPqZ6ul
zPRuy+fX7kn87FrxrrVxYWFrHFJeadLd362wmggW4l2AM7NHGFkzlUIGVzzyKzWsor1b+V0vxs/T
saWtGTXS34tf5v5rqZGseIzF/Y9ha+IdRWKeG4uJr6OwWa8fy2VfL8kQkKQznd+7yoQg4OTTlvLW
1kn3WvV+Wmu2rWq2aSsl3bt+v37W30u9dzstEn+06PZz/bYr/wAyFW+1QpsSbI++Bk4B64zWlRcs
mrWIg7rcyvtdt/z8Rf8AfYoAxL3S4p7qbytTgis7maOe4hKhmZ02/dfd8oOxc8HocYzRHRrsndf1
66/8AJap92rfL/O2ht/a7b/n4i/77FAF/S5YW0vYZo13NIM7h3dqyqR54uPcuL5WmYR8My22laJD
pGuwWl/pNmbIXMluJVljZFDfJvGDlEYfMcEd81dV+0nJvRS0f/Afda9OuwRaW/e/5/hr5dDQOmSW
nhwaNomrQ2McNkLa3naLzJImAwJPvAHjtgc857UqrdRt7Xt/wV92i7efRU3yNN6vW/m+/wB97/oU
9G0bU9K0U6dba7pVv5e0wPbaeV+YNljLvmcyb/4jlWOSd2eaqTvt/wAC3a35W281oJK179fvv3/p
fcX9HsJdP+0XEupWc19fXKz3ciwlI2ARUConmEp8qLyWbnJxzgLRJRWyv+P/AAfw031G7t3fkl6X
/wCC/wCkZ2h6Jqemavd3s2vaXc/bZS88hsGW4Kc7I1kMxVVXPA2Y6nGSSZimocj/AA6vv1/4bTYc
nefMv6Xbp/w+okuhapcB5rrxPatfw2klrZXcdmEaHzCu6R18zDv8i42hADnjkADV4u2jdr+i6Lqr
9732+bTs11Sd/nrb7r9tS14a0y+0TTDYjU9HMaKPJ8ixePDZyzPunYuW5JOQckkk1bd+nb0t2Xby
7dmZpW6/8P3/AK/AXVNKutSvDHc63bvpDTxXBtWtx5ytGysqrKHAC7kBOUY8sN3TCh7rTe62/wCD
6X8ul763qWzS0urf5/ejoPtEH/PaP/voUgD7RB/z2j/76FAB9og/57R/99CgDn/Hc8J0S2AlQ/8A
E107+If8/sFAGlrUCalp0ltBqclhMSrx3FvIAyMpBHHRhkYKngjIpO6s1uvu+f8AXo09Rq2qf9eh
hXnhqXWRcnxHrNncSSWU1lCbK1+ziNZQN7HdI5Y/KuOQOOh6gasm46PT8Hdaev8Akra3cJOMot7J
3/T8v62tC3hS4umu7nU9ftZr+WO1EMsNoI0he3kd0bYZG3Al+Rkd8EZGLvZ3jvdv71ytelvO5mor
lUHslb8n96a9PLe9y50bULuK2ubnxBaNq1ncme3mFmBbxgoUMflb9xUqSeZM7ucgDbUr3WmuzT80
3f5Wsremt7laNNPbS3quv5/Lz1Kmu+El1uGwm1LUNK1DUbQSqZNQ05J7dlkIJCw7xtI2qFO4kAEE
tnNKyvddrPv6+XXpby0GpaWfe/8AX9b/AHDNe8Fw6rZWNimpaelraW6wKZdPiaWAjGZLd0KeS5wO
QGUELhRjm+b977TzT89Ol+3/AAdRLSHL6+mvl5aljWPC6ap4jttTl1OxCW0sUkbmzT7ZEEOfLS4D
AiNj95SrEhnGcEYVP3Jc3r+Ktr3tfTboKSvDk8v13Xmb2kww6fbyxGe1IeeWYeUCg+dy5yCzZOWO
TkAnoB0pLSKXZDesm/62S/Qu/aIP+e0f/fQoAPtEH/PaP/voUAH2iD/ntH/30KAD7RB/z2j/AO+h
QAfaIP8AntH/AN9CgA+0Qf8APaP/AL6FAB9og/57R/8AfQoAjinhDy5lQZfj5h/dFAFWa2tpNatt
RMtuWt4JYVyTuG8oTg7toHyc5UnpgjkFx92/nb8L/wCf/D9Bu6S87/hYvfaIP+e0f/fQpAH2iD/n
tH/30KAD7RB/z2j/AO+hQAfaIP8AntH/AN9CgA+0Qf8APaP/AL6FAB9og/57R/8AfQoAPtEH/PaP
/voUAH2iD/ntH/30KAD7RB/z2j/76FAB9og/57R/99CgA+0Qf89o/wDvoUAH2iD/AJ7R/wDfQoAP
tEH/AD2j/wC+hQAfaIP+e0f/AH0KAD7RB/z2j/76FAB9og/57R/99CgA+0Qf89o/++hQAfaIP+e0
f/fQoAPtEH/PaP8A76FAB9og/wCe0f8A30KAD7RB/wA9o/8AvoUAH2iD/ntH/wB9CgA+0Qf89o/+
+hQAfaIP+e0f/fQoAjlnh3xYlTh+fmHHymgDE8ZaVN4gs7e1tdVs7WBJhJcQ3EBnjuVA4jcLIh25
wSM4OMHjIKs1JS7fn0fy/PXdDv7rXf8Ap/f+RQ1bQtX1OTTZJ9f0YiwLP9nbTHNvJJkbHKfaAcoO
gJIyc4yBik2p83l9z6teq07766smy5OTp+nb+vLsaH9iw3kGqLrV9b3UmqWq2szQJ5IWMKwwoLNj
l3PXv3xUyXuOMdNb37Oy/K1yoycZqXb/ADb/AB0T72Ktj4fuUtNUbUdegutSv7NbJLqO3ESwxqrB
Ts3nLbnZidwzkAAYoqpVIShtzO7+dlp20231bCm/Zyi1tHb+u706dDTXTLRX0cLdRCDSVIjj45by
/LVs54wpYYwfve1aSm5VJVO9/wAWn+hnGPLTUO1vwT/Wz9UjK0PRNS03V7u9udc0q8F7KXuGawdZ
2TnZGJPPIVVBwBtx1OMkms4r93yS179Lvv8A100RcnefMtO3kv6/HUf4a8ODR723ludYivLfT7Zr
TT4hEIzBEzAkO2472wiKCAvC9MmrUnZt6t2u/T/O938rWCWr02u383/lrb11uauk2UGnXuq3H2yO
T+0boXG3geXiKOPbnPP3M5460lpBR7X/ABbf6hJ3lzeSX3XDw9ZQaNYPa/bI5t1zPPu4XHmStJjG
T03Yz3x2o+zFdkl9ysDd5OXf/JIJ7KCXxHaav9sjX7NazW/lcfN5jRtuznjHl9Md/aiPu83nb8L/
AOYSd4pdnf8ACw1LFIde1DVYr6ESXdrDbqjLkRmMyEMfmGQfM6cdOvPC1UHFdXf8Ev0G2m436X/G
xk6rouqXfiGDVodd0kfZoQkEF1p7zJC5+/IuJ1wzdMnJA4B5ORe65NdfvS7f57X07IT1ik+n4vv8
uhrxWUY8QnVpr2J2+xrarGAAFO8szZyevy8dtvU01aPNbrb8L/5sT1Ub9L/jb/INRXUZoQdP1qzt
J0mLqXthJG8eCNjrvDEjOdysvIHGMgzrp/X9fj102s9Nf6/r+vnkJ4aezjt7jStYtrfVYzOZbiWD
zIpfPfzJP3YkBA3gFfmOAMHdzRJacsdFZL7tn66vy1em1ne7vLV3v+Frelkvmkzc0G0tNF0az02G
5EiWsSxh3YZfA5Jx6nmrk03orLp6LRfgSr9Xq7v5vVlSmIKACgDQ0X/kHr/10k/9DapY0XaQwoAK
ACgAoAKACgAoAKACgAoA5/x5/wAgO2/7Cum/+lsFAHQUAFABQAUAFABQAUAFABQAUAFABQAUAFAB
QBHD/rJv9/8A9lFAElABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFAE
c3+sh/3/AP2U0ASUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAf//Z')
	#endregion Binary Data
	$pictureboxExel.BackgroundImageLayout = 'Zoom'
	$pictureboxExel.Cursor = "No"
	$pictureboxExel.Location = '297, 60'
	$pictureboxExel.Name = "pictureboxExel"
	$pictureboxExel.Size = '219, 54'
	$pictureboxExel.SizeMode = 'StretchImage'
	$pictureboxExel.TabIndex = 9
	$pictureboxExel.TabStop = $False
	#endregion pictureboxExel
	#region trackbarDelai
	$trackbarDelai.Cursor = "SizeWE"
	$trackbarDelai.LargeChange = 20
	$trackbarDelai.Location = '365, 187'
	$trackbarDelai.Maximum = 2000
	$trackbarDelai.Minimum = 100
	$trackbarDelai.Name = "trackbarDelai"
	$trackbarDelai.Size = '104, 42'
	$trackbarDelai.SmallChange = 5
	$trackbarDelai.TabIndex = 8
	$trackbarDelai.TickFrequency = 100
	$trackbarDelai.Value = 200
	$trackbarDelai.add_Scroll($trackbarDelai_Scroll)
	#endregion trackbarDelai
	#region statusbar
	$statusbar.Location = '0, 320'
	$statusbar.Name = "statusbar"
	$statusbar.Size = '516, 22'
	$statusbar.TabIndex = 7
	$statusbar.Text = "status:"
	#endregion statusbar
	#region labelFileSearch
	$labelFileSearch.AutoSize = $True
	$labelFileSearch.Location = '33, 7'
	$labelFileSearch.Name = "labelFileSearch"
	$labelFileSearch.Size = '99, 13'
	$labelFileSearch.TabIndex = 6
	$labelFileSearch.Text = "choix fichier EXEL :"
	#endregion labelFileSearch
	#region labelFin
	$labelFin.AutoSize = $True
	$labelFin.Location = '33, 205'
	$labelFin.Name = "labelFin"
	$labelFin.Size = '24, 13'
	$labelFin.TabIndex = 5
	$labelFin.Text = "fin :"
	#endregion labelFin
	#region labelDebut
	$labelDebut.AutoSize = $True
	$labelDebut.Location = '33, 158'
	$labelDebut.Name = "labelDebut"
	$labelDebut.Size = '40, 13'
	$labelDebut.TabIndex = 4
	$labelDebut.Text = "début :"
	#endregion labelDebut
	#region comboboxFin
	$comboboxFin.Cursor = "Hand"
	$comboboxFin.FormattingEnabled = $True
	$comboboxFin.Location = '33, 224'
	$comboboxFin.Name = "comboboxFin"
	$comboboxFin.Size = '171, 21'
	$comboboxFin.TabIndex = 3
	$comboboxFin.Visible = $False
	$comboboxFin.add_SelectedIndexChanged($comboboxFin_SelectedIndexChanged)
	#endregion comboboxFin
	#region comboboxDebut
	$comboboxDebut.AutoCompleteMode = 'SuggestAppend'
	$comboboxDebut.Cursor = "Hand"
	$comboboxDebut.FormattingEnabled = $True
	$comboboxDebut.Location = '33, 181'
	$comboboxDebut.Name = "comboboxDebut"
	$comboboxDebut.Size = '171, 21'
	$comboboxDebut.TabIndex = 2
	$comboboxDebut.Visible = $False
	$comboboxDebut.add_SelectedIndexChanged($comboboxDebut_SelectedIndexChanged)
	#endregion comboboxDebut
	#region checkboxDNS
	$checkboxDNS.Cursor = "Hand"
	$checkboxDNS.Location = '33, 261'
	$checkboxDNS.Name = "checkboxDNS"
	$checkboxDNS.Size = '104, 24'
	$checkboxDNS.TabIndex = 1
	$checkboxDNS.Text = "résolution DNS :"
	$checkboxDNS.UseVisualStyleBackColor = $True
	#endregion checkboxDNS
	#region buttonLancer
	$buttonLancer.Cursor = "Hand"
	$buttonLancer.Location = '416, 245'
	$buttonLancer.Name = "buttonLancer"
	$buttonLancer.Size = '88, 35'
	$buttonLancer.TabIndex = 0
	$buttonLancer.Text = "Lancer"
	$buttonLancer.UseVisualStyleBackColor = $True
	$buttonLancer.Visible = $False
	$buttonLancer.add_Click($buttonLancer_Click)
	#endregion buttonLancer
	#region notifyicon
	$notifyicon.BalloonTipIcon = 'Info'
	#region Binary Data
	$notifyicon.Icon = [System.Convert]::FromBase64String('AAABAAYAICAQAAEABADoAgAAZgAAABAQEAABAAQAKAEAAE4DAAAgIAAAAQAIAKgIAAB2BAAAEBAA
AAEACABoBQAAHg0AACAgAAABACAAqBAAAIYSAAAQEAAAAQAgAGgEAAAuIwAAKAAAACAAAABAAAAA
AQAEAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAIAAAACAgACAAAAAgACAAICAAACA
gIAAwMDAAAAA/wAA/wAAAP//AP8AAAD/AP8A//8AAP///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACHd3d3d3iIiIiId3d3d3
gAiIiIiI////////iIiIiIAIhzMzMzMzMzMzMzMzMziAAIh7u7u7uzNzu7u7u7N4AACIe7u7u7sw
Rzu7u7uziAAACIe7u7u7MAM7u7u7N4AAAAiIu7u7uzMzu7u7sziAAAAAiHu7u7szM7u7u7OIAAAA
AAiLu7u7MAe7u7s3iAAAAAAIh7u7uxADu7u7OIAAAAAAAIh7u7sQADu7s4gAAAAAAACIi7u7MAA7
u7P4AAAAAAAACPe7uzADu7s4gAAAAAAAAACIu7s0ALu7f4AAAAAAAAAAj4u7d3U7s4gAAAAAAAAA
AAiLu3d3O7f4AAAAAAAAAAAIiLt3dzs/gAAAAAAAAAAAAIg7d3c7iAAAAAAAAAAAAAAIizd3s4gA
AAAAAAAAAAAACIe7u7iAAAAAAAAAAAAAAACIu7s4gAAAAAAAAAAAAAAAiHu7iAAAAAAAAAAAAAAA
AAiLt4gAAAAAAAAAAAAAAAAIh7iAAAAAAAAAAAAAAAAAAIiIAAAAAAAAAAAAAAAAAAAIiAAAAAAA
AAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP////////////////////+AAAABgAAA
AYAAAAHAAAADwAAAA+AAAAfgAAAH8AAAD/gAAA/4AAAf/AAAP/wAAD/+AAB//wAAf/8AAP//gAD/
/4AB///AA///4AP//+AH///wB///8A////gP///4H////D////4////+////////KAAAABAAAAAg
AAAAAQAEAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAIAAAACAgACAAAAAgACAAICA
AACAgIAAwMDAAAAA/wAA/wAAAP//AP8AAAD/AP8A//8AAP///wAAAAAAAAAAALMzMzMzMzM7u7u7
u7u7u7uDu7uwC7u7OAu7u7ALu7uwCDu7u7u7s4AAu7uzO7u7AAADu7ALuzAAAAu7sAu7sAAAADuw
C7MAAAAAu7ALuwAAAAADu7swAAAAAAu7u7AAAAAAADuzAAAAAAAAu7sAAAAAAAADMAAAAP//AAAA
AAAAAAAAAAAAAACAAQAAgAEAAMADAADgBwAA4AcAAPAPAADwDwAA+B8AAPgfAAD8PwAA/D8AAP5/
AAAoAAAAIAAAAEAAAAABAAgAAAAAAAAEAAAAAAAAAAAAAAABAAAAAQAAAAAAAAQAAAAMAwMAFgkI
ACIZFwAkHx4AMxsWADUkIAA4KikAKTg6ADs1NAA8ODcAMTs9ADo9PgBEODUAADlFAAA9TQAAQlUA
AEpdABVKUwAkQ0wAPUVGAD1PUwAAWnYALV5lADhaZAA6Z2wAQUBAAEtGRQBPTk0AVktKAEpUVQBE
VVoAW1dWAFddXwBkXFsAdF5eAEVucABDcnQARX1/AFFxdABbdXYAamVlAGVtbQBxZ2cAe2VkAAZl
gAAAcJAAPoadADOVmAAAibQAFou4AB+PuwAAkbsAI4izADaMsQAjkbYAN5a8AD6muwBOlrUAZJmw
AHWesQBDpbsASaS/AEytvQBTqrYAUKW5AGWrugB3q7MAc6q2AG2yuAAGi8MABpfOAACcywAGnNEA
A5jaABmf0QAhmMQAI5vJACaayAAinsoAJJ7LACKezQADpM0ABa3PABuiwwAeoskAH7fEAB64xwAV
tMsAGrXJAACh0QACqtQADa7RAACi2wALvNIABrDYABG30gAro8AAJqLLACCkzAAxrMQAILfGAD22
xgAAo+YAAKvlAACm6QABq+sAA7nkAACx7AAAu+0AALPyAAC78gAhuOwAKb7yACm/9ABFq8MAQ63D
AGSrwgB3q8IAZrfDAHm2xQAOwNEAB8rcAA3O3AARxtYAHcLXABXF3gAKxuYADcrkAADC7QAAyO4A
BtPgAAbb5AABwvEAAMjxAAXI8wAAyvYAAM31AAXM9QAAy/sAAdP1AAvT9wAI1/kABtn/AAvb+wAR
1/UAKML3ACTM9wAnwvkAIsr4ACbN+AAgzv8AKNH4ACPZ/gAG5PMABuX/AArr+QAT4/8AGeT+ABXq
/wAZ6/8AAfX8AA7w/wAA/v8AEvX/ABnw/wCal5cAm5iXAJqYmACcmpgAnpybAJ6dnACgnZ0AoqGd
AI2ruQCQsLUAo6GhAKSioQCnp6cArK6uALOurgC1rq4Av66tALSwrwCgr7EApra2AKC4vQCsuLgA
tbKxALiysgC9srIAu7SzAL60sgC5trYAvra1ALC0ugC3v78Aurq6AL+7vAC9vLwAwrS0AMS3tADB
ubcAxbu2AMu4tQDDursAx7m4AMG8ugDAvr0Ax769AMu8uQCMtsgAl7/BAIzExwCdw8cAnMPKAKzC
wgC7xcsAscnJAL7S2gDDwsIAy8XEAM7IxQDFycgAycnJAMzKyQDOzs0A08TDANTIxQDay8YA2M3L
AN3QywDKztIAz87QAM3P1ADO0dUA19fWANHU2ADX2NgA1trdANja3wDj1dQA5dnYAN3f4wDj5OcA
6ObnAObn6gDn6u0A7unoAOrr7gDq7e8A9OvpAOvt8AAAAAAA////AAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMat
p6enqKqqqq2trrGxsbGxsbGura2qqqqqqKqqsQAAveLp6enp7Ozw9Pf6+vr9/fr6+PX18e7s7Onp
6enRAADGy0VkZGRRUVFRUVFRUU00TVFRUVFRUVFRUVE5xL0AAAC1uXSamZmXl5SXl5dWFB8wcZNy
cnJycnKVTDzBAAAAAMbKRWCIiIiIhnBwiBECDiJKb2tra2tra2g2xsEAAAAAALjBPoKGhoKCgoJw
FwAGGV5ra2poaGhqRz3LAAAAAAAA4dOwYIiGhoaCgnBJLy4yb2tra2hoaEs35NEAAAAAAAAAveRC
hoOGhoaGiFsyNUlpbWtra2prR6/LAAAAAAAAAAAAwbxdiIOGhoiIEgAHIGBwbWtra0s75uAAAAAA
AAAAAADG80ODiIiGiIgQAAQWYHBtbW1rM9rRAAAAAAAAAAAAAADB8HSckY2Ngw8AAglTcIJtb0h3
6AAAAAAAAAAAAAAAAODy13+hn5+SEwMFDFSMiIhwOPrRAAAAAAAAAAAAAAAAAMH6QKOhoZ0YCAoV
YZCIiFPU5wAAAAAAAAAAAAAAAAAAAOHbf6OmnRoOCw1ZkY5sP/zgAAAAAAAAAAAAAAAAAAAAwfx4
m6WdJR4cG1qej1Xc3wAAAAAAAAAAAAAAAAAAAAAA0eB+pKIoIyEdWqCAdvziAAAAAAAAAAAAAAAA
AAAAAADg8taEoiksKiNmnWL20QAAAAAAAAAAAAAAAAAAAAAAAADB4meiKy0tJFeBeeUAAAAAAAAA
AAAAAAAAAAAAAAAAAADR1XsxJiYnfGXl0QAAAAAAAAAAAAAAAAAAAAAAAAAAAL3kQKSioqRf2NEA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAMG6e6SkpDrk4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4MpB
pKR6u8EAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAtbR9hUDN4gAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAADit0ZYxsEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC4xdnBAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAADB0eIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAO0AAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////////////////////gAAA
AYAAAAGAAAABwAAAA8AAAAPgAAAH4AAAB/AAAA/4AAAP+AAAH/wAAD/8AAA//gAAf/8AAH//AAD/
/4AA//+AAf//wAP//+AD///gB///8Af///AP///4D///+B////w////+P////v///////ygAAAAQ
AAAAIAAAAAEACAAAAAAAAAEAAAAAAAAAAAAAAAEAAAABAAAAAAAAHGhxAA+MqQAVqcoAFqvNABes
zQAYrs8AJq7OACG51QAku9YAJr/ZADe00QBHu9UAKcLbACvG3wAsxt0AEsDwABXC8AAWxPEAGMXx
ABvI8QAeyvIAJcXjACHD5AAmxuQAKsfgACXJ6QAhzPIAJtHzACfS9AAo0/QALNb0ADPa8wAw2fUA
NNv0ADvi9wA84/cAPuT3AD/m+AByyt8AReXxAEDl9QBH6vYASOjzAEjq9QBL7PUARer5AEnu+QBL
8PoATvL6AFH0+wBb9vsAgtDiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///8AAAAAAAAAAAAAAAAAAAAAAAwCAgICAgIC
AgICAgICAgwLGhMRERERERERERERERcLJwYbFBMREQAAExQUFBsEJwALFxwbFBQAABscHB4XCwAA
NAQiIh4eHh4iIiIiBDQAAAALDiYlJQEBJSUlGQsAAAAAAAQqMC8AAC4uKQQAAAAAAAALDjAwAAAv
Lw4LAAAAAAAAAAQsMgAAMCwEAAAAAAAAAAALCjMAADIOCwAAAAAAAAAAAAQsMjIsBAAAAAAAAAAA
AAALCTIyDgsAAAAAAAAAAAAAAAQpLAQAAAAAAAAAAAAAAAALCQ4LAAAAAAAAAAAAAAAAAAcHAAAA
AAAAAP//AAAAAAAAAAAAAAAAAACAAQAAgAEAAMADAADgBwAA4AcAAPAPAADwDwAA+B8AAPgfAAD8
PwAA/D8AAP5/AAAoAAAAIAAAAEAAAAABACAAAAAAAIAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAuAAAALgAAAC4A
AAAuAAAALgAAAC4AAAAuAAAALgAAAC4AAAAuAAAALgAAAC4AAAAuAAAALgAAAC4AAAAuAAAALgAA
AC4AAAAuAAAALgAAAC4AAAAuAAAALgAAAC4AAAAuAAAALgAAAC4AAAAuAAAALgAAAAAAAAAAi4qL
lJmYmO2UkpLxlpKS8ZaSkvGWk5Lxl5ST8ZeWlPGZl5bxnJeX8ZyYl/GdnJjxnpyc8Z6cnPGfnZzx
n52d8Z+dnPGenJzwnpyc8J2cmPCcmJfwm5eX8JiXlvCXlZTwl5ST8JaTkvCVkpHwlZKS8JSTk/GS
kpLNCgkJIAAAAACko6LRzMrJ/8nP0v/Kz9P/y8/T/83P1P/O0dX/z9LW/9ba3f/d3+P/5ufq/+rr
7v/q7e//6+3v/+vt8P/r7vD/6+3v/+vt7//n6u3/4+Xn/+Pk5//Y2t//0dTY/8/S1v/O0dX/zc/U
/8vO0//Nz9T/z87Q/8C8vPs5ODhFAAAAAKOiorvAuLf/c6q2/yCkzP8mo8v/JqHL/yafy/8knsv/
JJ7L/ySey/8jnsv/Ip7K/yKeyv8ins7/IpjE/x+Pu/8gmMX/I5vJ/yabyP8mmsj/JprI/yabyP8m
m8n/JpvJ/yabyf8mm8r/Ip7M/zeWvP+wtLr/rqmn4Y+OjiIAAAAAlpeXOLCrqvOgr7H/RavD/yPZ
/v8p0/j/KND4/yfO+P8mzfj/JMz3/yPL+P8iyvj/IM7//x6iyf8kQ0z/SlRV/z6Gnf8huOz/KML3
/ym98/8qvfL/Kr/z/ym/8/8pv/P/Kb/0/yfC+f8Zn9H/ZJmw/7+0sv+XlpVuAAAAAAAAAAAAAAAA
n56ersS3tP93q7P/BrDY/wXI8/8GxfD/BcPw/wLB8P8BwO//ALzw/wC99P8AwPX/AEJV/woAAP9E
OTT/V11f/wac0f8As/P/BK7r/wWs6/8Gq+r/Bqvq/wWr6/8GrOz/A6Lh/yOIs/+/u7z/p6KgxJCP
kA8AAAAAAAAAAAAAAACWlpYgrqin5bi3t/9Dpbv/Ar/r/wDE7v8Awe7/AL/u/wC97v8Auu3/ALrv
/wC99P8AWnb/BQAA/zMbFv84WmT/AKLb/wCs7v8AqOr/AKfo/wCk5/8ApOf/AKTn/wCm6/8Gi8X/
dZ6x/8S6tfmVlZVNAAAAAAAAAAAAAAAAAAAAAAAAAACcm5qNy7y5/5Cwtf8GrtX/AMjw/wDD7v8A
wu7/AMHu/wC97f8Au+3/ALvy/wCezf8AcJD/BmWA/wCKtv8AtPT/AKvr/wCp6v8AqOr/AKbn/wCk
5/8Ao+f/A5jc/zaMsf/TxcL/oZ+fqgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJaWlhCopaTX0cXE
/1Cluf8Cwer/AMjv/wDF7v8AxO7/AMLu/wDB7v8AwPD/AKHR/wCIs/8Akbv/AJvK/wCr5f8Ase3/
AK7r/wCs6v8Aqer/AKfo/wCo7f8Gi8L/jau5/8C3s/CYmJg0AAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAJaXl0+/tbT8rLi4/w2u0f8Azfb/AMnv/wDG7/8AxO7/AMXy/wDJ9v8ASl3/BAAA/zUk
IP9EVVr/AajU/wC49P8AsO3/AK/s/wCs6/8ArOz/A5nZ/06Wtf/ay8b/mJeXiQAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAl5eXBaKfn7zl2dj/Zau6/wLJ7P8AzfT/AMrw/wDG7v8AyPP/
AMby/wA9Tf8AAAD/IhkX/z1PU/8BqdP/ALr0/wCy7f8Ase3/ALDs/wCu7f8Wi7j/u8XL/7WwrtiS
kpIbAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAlZWVLLiysezX2Nj/Q63D/wbl
//8K2vj/AtP0/wDT9/8Aye//ADlF/wAAAP8PBwb/KTg6/wGmzf8Av/X/ALjt/wC07f8AtPD/BpfO
/3erwv/d0Mv/mJeYYwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
n52douTV1P+dw8f/FMTf/xjr//8b5P3/GOT//xHX9f8VSlP/FgkI/yQfHv8xOz3/Ba3P/wDL+/8A
w/D/AMHw/wC58P8jkbb/7uro/6+qqcOamZkPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAACTlZUbsq6t4e/p6P9Pr7//DfD//xrq//8b7P//Dej4/y1eZf84Kin/OzU0
/z1FRv8Rt9L/Btn//wXM9f8Ay/f/BqPO/4y2yP/Xy8n0kpKSSQAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACWl5dlzsPC/LHJyf8Xxt3/D/D//xnw//8K
6/j/Omds/0Q4N/88ODf/Oj0+/xW0y/8N3f//C9P3/wO55P9JpL//9u7t/6ShoaKXlpYDAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJWVlQenpaXK8uno
/2a3w/8G5PP/EvX//wrs+P9FbnD/VktK/0tGRf9BQED/GLTJ/xPj//8I1/n/G6LD/77S2v/Kw8Dp
l5eXLgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAJOVlT/FvLv2xcnI/x3C1/8B/f//BfT8/1FxdP9mW1r/W1dW/09OTf8dt8n/Fer//wrG
5v9kq8L/9ero/5uamogAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAl5eXAqGhoZri1tX/jMTH/wbT4P8D8/n/W3V2/3FnZ/9qZWX/
Yl5d/yC3xv8I7v//K6PA/+jm5/+3sK/WmJeXGwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAlZWVKLWwsOrOzs3/PbbG/wD0
+v9lbW3/fmVl/3hlZP90Xl7/H7fE/w3K5P95tsX/1cjF/pKRkWIAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
mZmZdse5uf+Xv8H/B8nb/zOVmP9EcXT/QnR1/0V9f/8Nztz/MazE/9PIxv+qp6a6m5qaBwAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAACVlpYRqaam2tTDw/9KrLz/AP///wD3//8A9///AP3//wu80v+cw8r/xri3
+JmYmUMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACXmJhYvbKy/Ka2tv8HzN3/AP///wD///8A
/f//Pqa7/9bEw/+dmZmdnp2dAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJeXlwOko6OuwrS0
/1Oqtv8A////AP///w7A0f+guL3/uKyr5o2OjisAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAJeYmDayq6v0rK6u/xHG1v8G2+T/Tay8/8u4tf+amZmBAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJudnYq/rq3/bbK4/x64x/+4u7v/q6KhzJ2bmxIAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAlpeXHKmmpeG3v7//rMLC/7ex
sfmamZlcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
np+fQrWxse/Durv/nZubi5eWlgIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAACdnpsFsbGvgK2srXidm5swAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///////////////8AA
AAGAAAAAgAAAAIAAAACAAAABwAAAAcAAAAPgAAAH4AAAB/AAAA/wAAAP+AAAH/wAAB/8AAA//gAA
P/4AAH//AAD//wAA//+AAf//wAH//8AD///gA///4Af///AP///4D///+B////wf///8P///////
KAAAABAAAAAgAAAAAQAgAAAAAABABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUqMrHD4yp/w+M
qf8PjKn/D4yp/w+Mqf8PjKn/D4yp/w+Mqf8PjKn/D4yp/w+Mqf8PjKn/D4yp/w+Mqf8UqMrHFKjK
2SXJ6f8ZxvH/FcLw/xPB8P8SwPD/E8Hw/xPB8P8TwfD/FMHw/xXC8P8Vw/D/FsPw/xfE8f8hw+T/
FKjK2RSoypkYrs//Is3y/xvI8f8YxfH/FsTx/xbD8P8AAAD/AAAA/xnG8f8byPH/Hsry/x7K8v8h
zPH/FqvN/xSoypkUqMobFKjK2SbG5P8m0fP/Ic3y/x/L8v8eyvL/AAAA/wAAAP8izfP/JtHz/yfS
9P8o0/T/JcXj/xSoytkUqMobAAAAABSoyocXrM3/NNv0/zDZ9f8t1/X/LNb0/yzW9P8u1/X/MNn1
/zDZ9f8y2/X/M9rz/xaqy/8UqMqHAAAAAAAAAAAUqMoSFKjK2SvG3/8/5vj/PuT3/z3j9/8caHH/
HGhx/zvi9/874vf/POP3/yrH4P8UqMrZFKjKEgAAAAAAAAAAAAAAABSoyngWqsv/R+r2/0vw+v9J
7vn/AAAA/wAAAP9F6vn/Rer5/0Dl9f8Wqsv/FKjKeAAAAAAAAAAAAAAAAAAAAAAUqMoMFKjK2SnC
2/9P8/v/TvH6/wAAAP8AAAD/Su/6/0rv+v8rxt//FKjK2RSoygwAAAAAAAAAAAAAAAAAAAAAAAAA
ABSoymkVqcv/Ser0/1H0+/8AAAD/AAAA/0/y+v9I6vb/FanL/xSoymkAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAUqMoGFKjK2Sa/2f9b9vv/AAAA/wAAAP9S9fv/Lcbd/xSoytkUqMoGAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAABSoyloUqcr/SOjz/1L1+/9S9fv/S+32/xWpy/8UqMpaAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUqMoDFKjK2SS71v9S9fv/UvX7/yzG3f8UqMrZFKjK
AwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABSoykgUqMr/ReXx/0vs9f8Vqcv/
FKjKSAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFKjK2SG51f8s
xt3/FKjK2QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABSo
yjkUqMrrFKjK6xSoyjkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//wAAAAAAAAAAAAAAAAAAAAAA
AIABAACAAQAAwAMAAMADAADgBwAA4AcAAPAPAADwDwAA+B8AAPw/AAD8PwAA')
	#endregion
	$notifyicon.Text = "notifyicon"
	$notifyicon.Visible = $True
	#endregion notifyicon
	#region errorprovider
	$errorprovider.ContainerControl = $formAuditIP
	#endregion errorprovider
	#endregion Generated Form Code

	#----------------------------------------------

	#Save the initial state of the form
	$InitialFormWindowState = $formAuditIP.WindowState
	#Init the OnLoad event to correct the initial state of the form
	$formAuditIP.add_Load($Form_StateCorrection_Load)
	#Clean up the control events
	$formAuditIP.add_FormClosed($Form_Cleanup_FormClosed)
	#Show the Form
	return $formAuditIP.ShowDialog()
} #End Function

#Call OnApplicationLoad to initialize
if((OnApplicationLoad) -eq $true){
	#Call the form
	Call-testTAB_pff | Out-Null
	#Perform cleanup
	OnApplicationExit
}
